/** @file settings_interface.h
 *
 * @brief Interface for the settings structures and functions. Allows for accessing settings
 * structures, updates from and to nvs. Included settings_def.h files are autogenerated and contain
 * settings structures defined in settings_types.h. Do not modify this file!
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2020 Irnas. All rights reserved.
 */

#ifndef SETTINGS_INTERFACE_H_
#define SETTINGS_INTERFACE_H_

// Zephyr
#include <stdio.h>
#include <zephyr/kernel.h>

// Settings
#include "thread_com.h"

/*!
 * @brief Init settings for device.
 *
 * Init NVS structure and overwrite stored values to Main_settings structure.
 *
 * @retval  Error on init. Return 0 if OK or -err.
 */
int init_settings(void);

/**
 * @brief Parse received message stream. It might consist of several messages, following structure:
 * id len msg[len].
 *
 * @param[in] uint8_t *message          Received message.
 * @param[in] uint8_t msg_length        Message length.
 * @param[in] uint8_t msg_origin        Message origin.
 * @param[in] uint8_t msg_port          Message port.
 * @param[in] uint8_t msg_max_rsp_len   Max rsp length.
 *
 * @retval  Error message in negative.
 * @retval  Length of return message if positive.
 */
int parse_settings_message(uint8_t *message, uint8_t message_length, mb_msg_dest message_origin,
			   uint8_t port, uint8_t msg_max_rsp_len);

/* Info functions */
void print_all_settings(void);

#endif /* SETTINGS_INTERFACE_H_ */

/*** end of file ***/
