"""This script will send get request to lora cloud server and receive almanac bytestream.

It will then convert this byte stream into c array and write it to almanac.c file.
"""

import os
from base64 import decodebytes

import requests

auth_token = os.environ.get("LR_ALMANAC_AUTH_TOKEN")
if auth_token is None:
    print(
        'Please set LR_ALMANAC_AUTH_TOKEN environment variable\n\n  export LR_ALMANAC_AUTH_TOKEN="<authorization token>"\n\nor provide it here:\n'
    )
    auth_token = input()
    if auth_token:
        auth_token = str(auth_token)
    if auth_token == "":
        print("No auth token found or provided, exiting...")
        exit()

auth_token = auth_token.strip('"')
auth_token = auth_token.strip("'")

URL = "https://mgs.loracloud.com/api/v1/almanac/full"

response = requests.get(URL, headers={"Authorization": auth_token})

print(response.json)
raw_almanac = response.json()["result"]["almanac_image"].encode()
almanac_bin = decodebytes(raw_almanac)

# Path to lr11xx_almanac.h file
path_h = "app/src/lorawan/almanac/lr11xx_almanac.h"
path_c = "app/src/lorawan/almanac/lr11xx_almanac.c"

print(len(almanac_bin))
print(almanac_bin[0])
print(hex(almanac_bin[0]))
print(hex(almanac_bin[2579]))

response = response.json()
with open(path_c, "w") as f:
    f.write("/* AUTOGENERATED FILE - DO NOT MODIFY! */\n")
    f.write('#include "lr11xx_almanac.h"\n\n')
    f.write("lr11xx_gnss_almanac_full_read_bytestream_t lr11xx_full_almanac = {\n")
    for i in range(len(almanac_bin)):
        if i % 19 == 0 and i != 0:
            f.write(hex(almanac_bin[i]) + ",\n")
        else:
            f.write(hex(almanac_bin[i]) + ", ")
    f.write("\n};")
    f.write("\n\n")

with open(path_h, "w") as f:
    f.write("/* AUTOGENERATED FILE - DO NOT MODIFY! */\n")
    f.write("#ifndef LR11XX_ALMANAC_H\n")
    f.write("#define LR11XX_ALMANAC_H\n\n")
    f.write("#include <zephyr/kernel.h>\n")
    f.write("#include <lr11xx_gnss_types.h>\n\n")
    f.write(
        "extern lr11xx_gnss_almanac_full_read_bytestream_t lr11xx_full_almanac;\n\n"
    )
    f.write("#endif")


print("Almanac bytestream received, almanac.c file was created!")
