#CONFIG_I2C=n
#CONFIG_SENSOR=n
#CONFIG_LIS2DW12_SENSOR=n
CONFIG_T5838=n
CONFIG_IRNAS_BMV080=n
CONFIG_IRNAS_BME69X=n
CONFIG_SDFS_UART_MODULE=n

CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_FPROTECT=n
CONFIG_REBOOT=n
