/* AUTOGENERATED FILE - DO NOT MODIFY! */
#ifndef COMMANDS_DEF_H_
#define COMMANDS_DEF_H_

#include "settings_types.h"
#include <stdio.h>
#include <zephyr/kernel.h>

#define CMD_JOIN                       0xA0
#define CMD_RESET                      0xA1
#define CMD_SEND_ALL_VAL               0xA2
#define CMD_SEND_SINGLE_VAL            0xA3
#define CMD_SEND_STATUS                0xA4
#define CMD_SEND_POSITION              0xA5
#define CMD_RESET_GPS                  0xA6
#define CMD_SEND_ALL_SETTINGS          0xA7
#define CMD_SEND_SINGLE_SETTING        0xA8
#define CMD_RESET_INITIAL_POSITION     0xA9
#define CMD_RESET_INITIAL_TIME         0xAA
#define CMD_CLEAR_NVS                  0xAB
#define CMD_RESET_TO_DEF_SETTINGS      0xAC
#define CMD_SEND_STATUS_LR             0xAD
#define CMD_SEND_LR_FIX                0xAE
#define CMD_SET_LOCATION_AND_TIME      0xAF
#define CMD_GET_WIFI_SCAN              0xB1
#define CMD_GET_BLE_SCAN               0xB2
#define CMD_GET_FLASH_STATUS           0xB3
#define CMD_GET_LR_SATELLITE_DATA      0xB4
#define CMD_GET_UBLOX_SATELLITE_DATA   0xB5
#define CMD_ALMANAC_UPDATE             0xB6
#define CMD_GET_MAC                    0xB7
#define CMD_GET_UBLOX_FIX              0xB8
#define CMD_RESET_LR                   0xB9
#define CMD_FLASH_CLEAR                0xBA
#define CMD_FLASH_GET_ALL              0xBB
#define CMD_FLASH_GET_FROM_HEAD        0xBC
#define CMD_S_BAND_SEND                0xBD
#define CMD_SET_OPERATION_MODE_COM_TH  0xBE
#define CMD_DISABLE_FLASH_TH           0xBF
#define CMD_DISABLE_BT_TH              0xC0
#define CMD_SET_OPERATION_MODE_MAIN_TH 0xC1
#define CMD_CHECK_PIN                  0xC2
#define CMD_SET_HIBERNATION_MODE       0xC3
#define CMD_SEND_LR_MESSAGE            0xC4
#define CMD_READ_ALL_LR_MESSAGES       0xC5
#define CMD_SEND_SAT_BUFFER            0xC6
#define CMD_LP0_COMMAND                0xC7
#define CMD_FENCE_MEASURE              0xC8
#define CMD_AGGREGATED_BT_SCAN         0xC9
#define CMD_SINGLE_BT_SCAN             0xCA
#define CMD_BT_DISCONNECT              0xCB
#define CMD_SEND_BT_CMDQ_RESULTS       0xCC
#define CMD_DECOUPLE_COLLAR            0xCD
#define CMD_SEND_TIMESTAMP             0xCE

#endif
