/** @file generated_settings.c
 *
 * @brief Interface for the generated settings structures and functions. Allows for accessing
 * settings structures, and checking ids. Included settings_def.h files are autogenerated and
 * contain settings structures defined in settings_types.h. Do not modify this file!
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2020 Irnas. All rights reserved.
 */

#include "generated_settings.h"

/*!
 * @brief Check if setting ID is in the Main_settings structure.
 *
 * @param[in] uint8_t id    Setting id.
 *
 * @retval  Return 1 if setting exist, 0 if not.
 */
uint8_t check_setting_id(uint8_t id)
{
	for (uint8_t i = 0; i < Main_settings.n_settings; i++) {
		if (id == Main_settings.settings_id[i]) {
			return 1;
		}
	}
	return 0;
}

// Check if ID is in the Main_values structure
/*!
 * @brief Check if value ID is in the Main_values structure.
 *
 * @param[in] uint8_t id    Value id.
 *
 * @retval  Return 1 if value exist, 0 if not.
 */
uint8_t check_value_id(uint8_t id)
{
	for (uint8_t i = 0; i < Main_values.n_values; i++) {
		if (id == Main_values.values_id[i]) {
			return 1;
		}
	}
	return 0;
}

/*!
 * @brief Check if ID is in the Main_settings structure and return its value length
 *
 * @param[in] uint8_t id    Value id.
 *
 * @retval  Return length if value exist, 0 if not.
 */
uint8_t get_setting_len(uint8_t id)
{
	for (uint8_t i = 0; i < Main_settings.n_settings; i++) {
		if (id == Main_settings.settings_id[i]) {
			return Main_settings.settings_length[i];
		}
	}
	return 0;
}

/*!
 * @brief Check if setting with this ID needs to be validated, if so check values
 *
 * @param[in] uint8_t id    Value id.
 * @param[in] data          New data.
 *
 * @retval  True if valid otherwise false.
 */
bool validate_setting(uint8_t id, uint8_t *data)
{
	if (id == Main_settings.tracker_type->id) {
		uint8_t set_type = data[0];
		// For all HW types default tracker type is valid
		if (set_type == default_tracker) {
			return true;
		}
#ifdef CONFIG_BOARD_RANGEREDGE_NRF52840
		if (set_type == rangeredge_tracker || set_type == fenceedge_tracker ||
		    set_type == scanneredge_tracker) {
			return true;
		}
		if (strcmp(CONFIG_BOARD_REVISION, "1.4.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.6.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.7.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.8.0") == 0) {
			if (set_type == elephantedge_tracker || set_type == wisentedge_tracker) {
				return true;
			}
		}
#elif CONFIG_BOARD_RANGEREDGE_AIRQ_NRF52840
		if (set_type == rangeredge_tracker || set_type == fenceedge_tracker ||
		    set_type == scanneredge_tracker) {
			return true;
		}
		if (strcmp(CONFIG_BOARD_REVISION, "1.4.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.6.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.7.0") == 0 ||
		    strcmp(CONFIG_BOARD_REVISION, "1.8.0") == 0) {
			if (set_type == elephantedge_tracker || set_type == wisentedge_tracker) {
				return true;
			}
		}
#elif CONFIG_BOARD_RHINOEDGE_NRF52840
		if (set_type == rhinoedge_tracker || set_type == horseedge_tracker ||
		    set_type == baboonedge_tracker || set_type == pangolinedge_tracker ||
		    set_type == collaredgepico_tracker || set_type == collaredgenano_tracker) {
			return true;
		}
#elif CONFIG_BOARD_RHINOPUCK_NRF52840
		if (set_type == rhinopuck_tracker || set_type == horseedge_tracker ||
		    set_type == baboonedge_tracker) {
			return true;
		}
#elif CONFIG_BOARD_RHINOPUCK35_NRF52840
		if (set_type == rhinopuck_tracker || set_type == horseedge_tracker ||
		    set_type == baboonedge_tracker) {
			return true;
		}
#elif CONFIG_BOARD_COLLAREDGE_NRF52840
		if (set_type == collaredge_tracker) {
			return true;
		}
#elif CONFIG_BOARD_FREEEDGE_NRF52840
		if (set_type == freeedge_tracker) {
			return true;
		}
#else
		LOG_ERR("Invalid HW type!");
#endif
		return false;
	}
	if (id == Main_settings.device_pin->id) {
		for (uint8_t i = 0; i < Main_settings.device_pin->len; i++) {
			if (data[i] > 9) {
				return false;
			}
		}
	}

	return true;
}

/*!
 * @brief Check if ID is in the Main_values structure and return its value length
 *
 * @param[in] uint8_t id    Value id.
 *
 * @retval  Return length if value exist, 0 if not.
 */
uint8_t get_value_len(uint8_t id)
{
	for (uint8_t i = 0; i < Main_values.n_values; i++) {
		if (id == Main_values.values_id[i]) {
			return Main_values.values_length[i];
		}
	}
	return 0;
}

/*!
 * @brief Get port number based on the message id
 *
 * @param[in] uint8_t id    Value id.
 *
 * @retval  Return send port, 0 if id is not valid.
 */
uint8_t get_message_port(uint8_t id)
{
	for (uint8_t i = 0; i < Main_messages.n_values; i++) {
		if (id == Main_messages.messages_id[i]) {
			return Main_messages.messages_port[i];
		}
	}
	return 0;
}

/*!
 * @brief Check if in lr send flag, port is marked as ok
 *
 *
 * @return true if send, false if not
 */
bool check_lr_send_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (port == Main_messages.msg_status->port) {
		return true; // Cannot disable status messages
	} else if (CHECK_BIT(Main_settings.lr_send_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}

/*!
 * @brief Check if in satellite send flag, port is marked as ok
 *
 *
 * @return true if send, false if not
 */
bool check_sat_send_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (CHECK_BIT(Main_settings.sat_send_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}

/*!
 * @brief Check if in store flag, port is marked as ok
 *
 *
 * @return true if send, false if not
 */
bool check_flash_store_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (CHECK_BIT(Main_settings.flash_store_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}

/*!
 * @brief Check if rejoin flag is active, port is marked as ok
 *
 *
 * @return true if send, false if not
 */
bool check_lr_join_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (CHECK_BIT(Main_settings.lr_join_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}

/*!
 * @brief Check if confirm flag is active, port is marked as ok
 *
 *
 * @return true if send, false if not
 */
bool check_lr_confirm_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (CHECK_BIT(Main_settings.lr_confirm_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}

bool check_lp0_send_flag(uint8_t port)
{
	// Check if port nr. is in specified check range
	if (port > 32) {
		return true; // Port is not controlled by send flag
	} else if (CHECK_BIT(Main_settings.lp0_send_flag->def_val, port - 1)) {
		return true;
	} else {
		return false;
	}
}
