/** @file generated_settings.h
 *
 * @brief Interface for the generated settings structures and functions. Allows for accessing
 * settings structures, and checking ids. Included settings_def.h files are autogenerated and
 * contain settings structures defined in settings_types.h. Do not modify this file!
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2020 Irnas. All rights reserved.
 */

#ifndef GENERATED_SETTINGS_H_
#define GENERATED_SETTINGS_H_

#include <stdio.h>
#include <zephyr/kernel.h>

#include "commands_def.h"
#include "messages_def.h"
#include "settings_def.h"
#include "values_def.h"

#define CHECK_BIT(var, pos) ((var) & (1 << (pos)))

/* Settings helper functions */
uint8_t check_setting_id(uint8_t id);
uint8_t check_value_id(uint8_t id);
uint8_t get_setting_len(uint8_t id);
bool validate_setting(uint8_t id, uint8_t *data);
uint8_t get_value_len(uint8_t id);
uint8_t get_message_port(uint8_t id);

/* Check send/store flag */
bool check_lr_send_flag(uint8_t port);
bool check_sat_send_flag(uint8_t port);
bool check_flash_store_flag(uint8_t port);
bool check_lr_join_flag(uint8_t port);
bool check_lr_confirm_flag(uint8_t port);
bool check_lp0_send_flag(uint8_t port);

#endif // GENERATED_SETTINGS_H_
