/* AUTOGENERATED FILE - DO NOT MODIFY! */
#include "messages_def.h"
#include <stdio.h>

cmd_message msg_lr_messaging = {28, 0x90, 250, BYTE_ARRAY};

cmd_message msg_memfault_chunks = {27, 0x91, 250, BYTE_ARRAY};

cmd_message msg_fence = {12, 0x92, 250, BYTE_ARRAY};

cmd_message msg_ublox_location_short = {13, 0x93, 14, BYTE_ARRAY};

cmd_message msg_flash_status = {14, 0x94, 5, BYTE_ARRAY};

cmd_message msg_ublox_resend_location = {16, 0x95, 14, BYTE_ARRAY};

cmd_message msg_timestamp = {18, 0x97, 4, UINT32_T};

cmd_message msg_external_switch_detection = {19, 0x98, 5, UINT32_T};

cmd_message msg_external_switch_detection_status = {20, 0x99, 5, BYTE_ARRAY};

cmd_message msg_air_quality = {21, 0x9A, 47, BYTE_ARRAY};

cmd_message msg_lp0_ping = {22, 0x9B, 14, BYTE_ARRAY};

cmd_message msg_lp0_commands = {33, 0x9C, 250, BYTE_ARRAY};

cmd_message msg_lr_messaging_timestamp = {28, 0xF0, 250, BYTE_ARRAY};

cmd_message msg_gnss = {1, 0xF1, 250, BYTE_ARRAY};

cmd_message msg_ublox_location = {2, 0xF2, 30, BYTE_ARRAY};

cmd_message msg_cmd_confirm = {31, 0xF3, 2, BYTE_ARRAY};

cmd_message msg_status = {4, 0xF4, 14, BYTE_ARRAY};

cmd_message msg_lr_satellites = {5, 0xF5, 250, BYTE_ARRAY};

cmd_message msg_ublox_satellites = {9, 0xF6, 250, BYTE_ARRAY};

cmd_message msg_wifi_scan_aggregated = {6, 0xF7, 250, BYTE_ARRAY};

cmd_message msg_wifi_scan = {10, 0xF8, 250, BYTE_ARRAY};

cmd_message msg_ble_scan_aggregated = {7, 0xF9, 250, BYTE_ARRAY};

cmd_message msg_ble_scan = {11, 0xFA, 250, BYTE_ARRAY};

cmd_message msg_ble_cmdq = {15, 0xFC, 250, BYTE_ARRAY};

cmd_message msg_mac_id = {31, 0xFD, 6, BYTE_ARRAY};

cmd_message msg_last_position = {31, 0xFE, 16, BYTE_ARRAY};

cmd_message msg_read_flash = {29, 0xFF, 250, BYTE_ARRAY};

uint8_t mes_id_array[] = {0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x97, 0x98, 0x99,
			  0x9A, 0x9B, 0x9C, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5,
			  0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFC, 0xFD, 0xFE, 0xFF};
uint8_t mes_len_array[] = {250, 250, 250, 14,  5,   14,  4,   5,   5,   47,  14, 250, 250, 250,
			   30,  2,   14,  250, 250, 250, 250, 250, 250, 250, 6,  16,  250};
uint8_t mes_port_array[] = {28, 27, 12, 13, 14, 16, 18, 19, 20, 21, 22, 33, 28, 1,
			    2,  31, 4,  5,  9,  6,  10, 7,  11, 15, 31, 31, 29};

main_messages Main_messages = {&msg_lr_messaging,
			       &msg_memfault_chunks,
			       &msg_fence,
			       &msg_ublox_location_short,
			       &msg_flash_status,
			       &msg_ublox_resend_location,
			       &msg_timestamp,
			       &msg_external_switch_detection,
			       &msg_external_switch_detection_status,
			       &msg_air_quality,
			       &msg_lp0_ping,
			       &msg_lp0_commands,
			       &msg_lr_messaging_timestamp,
			       &msg_gnss,
			       &msg_ublox_location,
			       &msg_cmd_confirm,
			       &msg_status,
			       &msg_lr_satellites,
			       &msg_ublox_satellites,
			       &msg_wifi_scan_aggregated,
			       &msg_wifi_scan,
			       &msg_ble_scan_aggregated,
			       &msg_ble_scan,
			       &msg_ble_cmdq,
			       &msg_mac_id,
			       &msg_last_position,
			       &msg_read_flash,
			       27,
			       mes_id_array,
			       mes_len_array,
			       mes_port_array};
