/* AUTOGENERATED FILE - DO NOT MODIFY! */
#ifndef MESSAGES_DEF_H_
#define MESSAGES_DEF_H_

#include "settings_types.h"
#include <stdio.h>
#include <zephyr/kernel.h>

#include "type_conversion.h"

#define PORT_LR_GPS                           1
#define PORT_UBLOX_GPS                        2
#define PORT_SETTINGS                         3
#define PORT_STATUS                           4
#define PORT_LR_SAT_DATA                      5
#define PORT_WIFI_SCAN_AGGREGATED             6
#define PORT_BLE_SCAN_AGGREGATED              7
#define PORT_UBLOX_SAT_DATA                   9
#define PORT_WIFI_SCAN                        10
#define PORT_BLE_SCAN                         11
#define PORT_FENCE                            12
#define PORT_UBLOX_SHORT_MESSAGE              13
#define PORT_FLASH_STATUS                     14
#define PORT_BLE_CMDQ                         15
#define PORT_UBLOX_RESEND_LOCATION            16
#define PORT_TIMESTAMP                        18
#define PORT_EXTERNAL_SWITCH_DETECTION        19
#define PORT_EXTERNAL_SWITCH_DETECTION_STATUS 20
#define PORT_AIR_QUALITY                      21
#define PORT_LP0_PING                         22
#define PORT_MEMFAULT                         27
#define PORT_LR_MESSAGING                     28
#define PORT_FLASH_LOG                        29
#define PORT_VALUES                           30
#define PORT_MESSAGES                         31
#define PORT_COMMANDS                         32
#define PORT_LP0_COMMANDS                     33

#define MSG_LR_MESSAGING_ID                     0x90
#define MSG_MEMFAULT_CHUNKS_ID                  0x91
#define MSG_FENCE_ID                            0x92
#define MSG_UBLOX_LOCATION_SHORT_ID             0x93
#define MSG_FLASH_STATUS_ID                     0x94
#define MSG_UBLOX_RESEND_LOCATION_ID            0x95
#define MSG_TIMESTAMP_ID                        0x97
#define MSG_EXTERNAL_SWITCH_DETECTION_ID        0x98
#define MSG_EXTERNAL_SWITCH_DETECTION_STATUS_ID 0x99
#define MSG_AIR_QUALITY_ID                      0x9A
#define MSG_LP0_PING_ID                         0x9B
#define MSG_LP0_COMMANDS_ID                     0x9C
#define MSG_LR_MESSAGING_TIMESTAMP_ID           0xF0
#define MSG_GNSS_ID                             0xF1
#define MSG_UBLOX_LOCATION_ID                   0xF2
#define MSG_CMD_CONFIRM_ID                      0xF3
#define MSG_STATUS_ID                           0xF4
#define MSG_LR_SATELLITES_ID                    0xF5
#define MSG_UBLOX_SATELLITES_ID                 0xF6
#define MSG_WIFI_SCAN_AGGREGATED_ID             0xF7
#define MSG_WIFI_SCAN_ID                        0xF8
#define MSG_BLE_SCAN_AGGREGATED_ID              0xF9
#define MSG_BLE_SCAN_ID                         0xFA
#define MSG_BLE_CMDQ_ID                         0xFC
#define MSG_MAC_ID_ID                           0xFD
#define MSG_LAST_POSITION_ID                    0xFE
#define MSG_READ_FLASH_ID                       0xFF

typedef struct main_messages {
	cmd_message *msg_lr_messaging;
	cmd_message *msg_memfault_chunks;
	cmd_message *msg_fence;
	cmd_message *msg_ublox_location_short;
	cmd_message *msg_flash_status;
	cmd_message *msg_ublox_resend_location;
	cmd_message *msg_timestamp;
	cmd_message *msg_external_switch_detection;
	cmd_message *msg_external_switch_detection_status;
	cmd_message *msg_air_quality;
	cmd_message *msg_lp0_ping;
	cmd_message *msg_lp0_commands;
	cmd_message *msg_lr_messaging_timestamp;
	cmd_message *msg_gnss;
	cmd_message *msg_ublox_location;
	cmd_message *msg_cmd_confirm;
	cmd_message *msg_status;
	cmd_message *msg_lr_satellites;
	cmd_message *msg_ublox_satellites;
	cmd_message *msg_wifi_scan_aggregated;
	cmd_message *msg_wifi_scan;
	cmd_message *msg_ble_scan_aggregated;
	cmd_message *msg_ble_scan;
	cmd_message *msg_ble_cmdq;
	cmd_message *msg_mac_id;
	cmd_message *msg_last_position;
	cmd_message *msg_read_flash;

	uint8_t n_values;
	uint8_t *messages_id;
	uint8_t *messages_length;
	uint8_t *messages_port;
} main_messages;

extern main_messages Main_messages;
#endif
