/* AUTOGENERATED FILE - DO NOT MODIFY! */
#include "settings_def.h"
#include <stdio.h>
#include <string.h>
#include <zephyr/sys/byteorder.h>

#define MAKE_KEY(family, id) (((family) << 8) | (id))
value_uint8 tracker_type = {0x00, 0, 0, 15, 1, UINT8_T, 0x02};

value_uint32 status_send_interval = {0x01, 3600, 1, 86400, 4, UINT32_T, 0x02};

value_uint32 init_time = {0x02, 1787788800, 1787788800, 4294967295, 4, UINT32_T, 0x02};

value_bool data_log = {0x03, true, false, true, 1, BOOL, 0x02};

value_uint32 wifi_scan_interval = {0x04, 0, 0, 86400, 4, UINT32_T, 0x02};

value_uint32 wifi_scan_aggregated_interval = {0x05, 0, 0, 86400, 4, UINT32_T, 0x02};

uint8_t device_name_def[8] = "";
uint8_t device_name_min[8] = "";
uint8_t device_name_max[8] = "";

value_byte_array device_name = {
	0x06, device_name_def, device_name_min, device_name_max, 8, BYTE_ARRAY, 0x02};

uint8_t device_pin_def[4] = {0x00, 0x00, 0x00, 0x00};
uint8_t device_pin_min[4] = {0x00, 0x00, 0x00, 0x00};
uint8_t device_pin_max[4] = {0x00, 0x00, 0x00, 0x00};

value_byte_array device_pin = {0x07, device_pin_def, device_pin_min, device_pin_max, 4, BYTE_ARRAY,
			       0x02};

value_bool led_enabled = {0x08, true, false, true, 1, BOOL, 0x02};

value_uint32 memfault_send_interval = {0x09, 0, 0, 86400, 4, UINT32_T, 0x02};

value_uint32 check_error_interval = {0x0A, 86400, 0, 2678400, 4, UINT32_T, 0x02};

value_uint32 flash_status_interval = {0x0B, 0, 0, 604800, 4, UINT32_T, 0x02};

value_bool wifi_scan_report_zero_connections_found = {0x0C, false, false, true, 1, BOOL, 0x02};

value_uint32 lr_send_flag = {0x00, 4162715375, 0, 4294967295, 4, UINT32_T, 0x03};

value_uint32 flash_store_flag = {0x01, 876143, 0, 4294967295, 4, UINT32_T, 0x03};

value_uint32 sat_send_flag = {0x02, 16522, 0, 4294967295, 4, UINT32_T, 0x03};

value_bool ble_adv = {0x00, true, false, true, 1, BOOL, 0x04};

value_uint32 ble_advertisement_interval = {0x01, 500, 100, 10000, 4, UINT32_T, 0x04};

value_uint32 ble_scan_duration = {0x02, 600, 50, 10000, 4, UINT32_T, 0x04};

value_uint32 ble_scan_interval = {0x03, 0, 0, 86400, 4, UINT32_T, 0x04};

value_uint32 ble_scan_aggregated_interval = {0x04, 0, 0, 86400, 4, UINT32_T, 0x04};

value_uint8 ble_scan_filter = {0x05, 1, 0, 4, 1, UINT8_T, 0x04};

value_uint32 ble_auto_disconnect = {0x06, 600, 0, 86400, 4, UINT32_T, 0x04};

value_bool ble_scan_report_zero_connections_found = {0x07, false, false, true, 1, BOOL, 0x04};

value_bool cmdq_enabled = {0x08, false, false, true, 1, BOOL, 0x04};

value_uint32 cmdq_scan_duration = {0x09, 10000, 1, 10000, 4, UINT32_T, 0x04};

value_uint32 cmdq_search_interval = {0x0A, 300, 1, 10000, 4, UINT32_T, 0x04};

value_uint32 cmdq_on_no_detection_wait_duration = {0x0B, 1800, 1, 10000, 4, UINT32_T, 0x04};

uint8_t cmdq_searched_mac_address_def[6] = {0xD8, 0x10, 0x68, 0xAC, 0xDA, 0xE4};
uint8_t cmdq_searched_mac_address_min[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t cmdq_searched_mac_address_max[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array cmdq_searched_mac_address = {0x0C,
					      cmdq_searched_mac_address_def,
					      cmdq_searched_mac_address_min,
					      cmdq_searched_mac_address_max,
					      6,
					      BYTE_ARRAY,
					      0x04};

value_uint32 cmdq_reporting_interval = {0x0D, 300, 1, 10000, 4, UINT32_T, 0x04};

value_bool cmdq_report_zero_messages_to_be_sent = {0x0E, false, false, true, 1, BOOL, 0x04};

value_uint16 ble_scan_manufacturer_id = {0x0F, 2657, 0, 65535, 2, UINT16_T, 0x04};

value_uint32 lr_gps_interval = {0x00, 0, 0, 86400, 4, UINT32_T, 0x05};

value_bool gnss_assisted_scan = {0x01, false, false, true, 1, BOOL, 0x05};

value_uint8 lr_adr = {0x02, 3, 0, 15, 1, UINT8_T, 0x05};

value_uint8 lr_region = {0x03, 1, 1, 13, 1, UINT8_T, 0x05};

uint8_t app_key_def[16] = {0x8B, 0xCD, 0x49, 0x42, 0x11, 0x67, 0xDD, 0x03,
			   0xBA, 0xD3, 0xAE, 0xEA, 0x98, 0xEF, 0xE4, 0x09};
uint8_t app_key_min[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t app_key_max[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array app_key = {0x04, app_key_def, app_key_min, app_key_max, 16, BYTE_ARRAY, 0x05};

uint8_t device_eui_def[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t device_eui_min[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t device_eui_max[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array device_eui = {0x05, device_eui_def, device_eui_min, device_eui_max, 8, BYTE_ARRAY,
			       0x05};

uint8_t app_eui_def[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t app_eui_min[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t app_eui_max[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array app_eui = {0x06, app_eui_def, app_eui_min, app_eui_max, 8, BYTE_ARRAY, 0x05};

value_uint32 s_band_send_interval = {0x07, 0, 0, 604800, 4, UINT32_T, 0x05};

value_uint32 lr_join_flag = {0x08, 0, 0, 4294967295, 4, UINT32_T, 0x05};

value_uint32 lr_confirm_flag = {0x09, 0, 0, 4294967295, 4, UINT32_T, 0x05};

value_uint16 lr_max_confirm_fail = {0x0A, 0, 0, 1000, 2, UINT16_T, 0x05};

value_uint32 lr_messaging_retry_interval = {0x0B, 60, 0, 86400, 4, UINT32_T, 0x05};

value_uint8 lr_messaging_retry_count = {0x0C, 1, 1, 5, 1, UINT8_T, 0x05};

value_uint32 rejoin_interval = {0x0D, 3600, 600, 86400, 4, UINT32_T, 0x05};

uint8_t lp0_app_key_def[16] = {0xEC, 0x7F, 0x38, 0x0E, 0x7A, 0xDF, 0xB2, 0xE5,
			       0xC9, 0xBB, 0xDE, 0x5A, 0xC2, 0x16, 0x94, 0xA8};
uint8_t lp0_app_key_min[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t lp0_app_key_max[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array lp0_app_key = {
	0x0E, lp0_app_key_def, lp0_app_key_min, lp0_app_key_max, 16, BYTE_ARRAY, 0x05};

uint8_t lp0_network_key_def[16] = {0xDB, 0x7E, 0x27, 0x26, 0xCF, 0xF5, 0x8C, 0x13,
				   0x3A, 0x07, 0xB5, 0xA1, 0xB4, 0x00, 0xE1, 0xD0};
uint8_t lp0_network_key_min[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
				   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t lp0_network_key_max[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
				   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array lp0_network_key = {
	0x0F, lp0_network_key_def, lp0_network_key_min, lp0_network_key_max, 16, BYTE_ARRAY, 0x05};

uint8_t lp0_dev_addr_def[4] = {0x26, 0x0B, 0xF6, 0xEF};
uint8_t lp0_dev_addr_min[4] = {0x00, 0x00, 0x00, 0x00};
uint8_t lp0_dev_addr_max[4] = {0x00, 0x00, 0x00, 0x00};

value_byte_array lp0_dev_addr = {
	0x10, lp0_dev_addr_def, lp0_dev_addr_min, lp0_dev_addr_max, 4, BYTE_ARRAY, 0x05};

value_uint32 s_band_rf_frequency_hz = {0x11, 2008450000, 1980000000, 2100000000, 4, UINT32_T, 0x05};

value_uint8 lr_adr_profile = {0x12, 3, 0, 3, 1, UINT8_T, 0x05};

value_bool vhf_enabled = {0x13, false, false, true, 1, BOOL, 0x05};

value_uint32 vhf_interval1 = {0x14, 2, 0, 86400, 4, UINT32_T, 0x05};

value_uint32 vhf_interval2 = {0x15, 2, 0, 86400, 4, UINT32_T, 0x05};

value_uint8 vhf_interval1_start = {0x16, 7, 0, 23, 1, UINT8_T, 0x05};

value_uint8 vhf_interval2_start = {0x17, 19, 0, 23, 1, UINT8_T, 0x05};

value_bool vhf_multiple_intervals = {0x18, false, false, true, 1, BOOL, 0x05};

value_uint8 vhf_num_of_packets_per_burst = {0x19, 1, 1, 255, 1, UINT8_T, 0x05};

value_uint16 vhf_time_between_packets_ms = {0x1A, 250, 1, 10000, 2, UINT16_T, 0x05};

value_bool vhf_external_path = {0x1B, false, false, true, 1, BOOL, 0x05};

value_uint32 vhf_tx_frequency_khz = {0x1C, 150000, 150000, 300000, 4, UINT32_T, 0x05};

value_uint16 vhf_single_pulse_duration_ms = {0x1D, 18, 5, 10000, 2, UINT16_T, 0x05};

value_uint8 s_band_send_mode = {0x1E, 1, 0, 2, 1, UINT8_T, 0x05};

value_uint32 lp0_send_flag = {0x1F, 0, 0, 4294967295, 4, UINT32_T, 0x05};

value_uint32 lp0_tx_frequency_hz = {0x20, 869150000, 0, 2100000000, 4, UINT32_T, 0x05};

value_uint32 lp0_rx_frequency_hz = {0x21, 869150000, 0, 2100000000, 4, UINT32_T, 0x05};

uint8_t lp0_communication_params_def[4] = {0x07, 0x05, 0x01, 0x01};
uint8_t lp0_communication_params_min[4] = {0x00, 0x00, 0x00, 0x00};
uint8_t lp0_communication_params_max[4] = {0x00, 0x00, 0x00, 0x00};

value_byte_array lp0_communication_params = {0x22,
					     lp0_communication_params_def,
					     lp0_communication_params_min,
					     lp0_communication_params_max,
					     4,
					     BYTE_ARRAY,
					     0x05};

uint8_t lp0_node_params_def[5] = {0x00, 0x00, 0x0a, 0x01, 0x3c};
uint8_t lp0_node_params_min[5] = {0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t lp0_node_params_max[5] = {0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array lp0_node_params = {
	0x23, lp0_node_params_def, lp0_node_params_min, lp0_node_params_max, 5, BYTE_ARRAY, 0x05};

value_uint32 ublox_send_interval = {0x00, 0, 0, 172800, 4, UINT32_T, 0x06};

value_int32 gps_init_lon = {0x01, 156447700, -1800000000, 1800000000, 4, INT32_T, 0x06};

value_int32 gps_init_lat = {0x02, 465556280, -900000000, 900000000, 4, INT32_T, 0x06};

value_uint32 gps_resend_interval = {0x03, 0, 0, 86400, 4, UINT32_T, 0x06};

value_uint32 horizontal_accuracy = {0x04, 50, 1, 1000, 4, UINT32_T, 0x06};

value_uint8 cold_fix_retry = {0x05, 200, 1, 255, 1, UINT8_T, 0x06};

value_uint8 hot_fix_retry = {0x06, 4, 1, 255, 1, UINT8_T, 0x06};

value_uint16 cold_fix_timeout = {0x07, 200, 1, 600, 2, UINT16_T, 0x06};

value_uint16 hot_fix_timeout = {0x08, 65, 1, 600, 2, UINT16_T, 0x06};

value_uint8 gps_backoff_factor = {0x09, 10, 10, 100, 1, UINT8_T, 0x06};

value_uint32 ublox_send_interval_2 = {0x0A, 0, 0, 86400, 4, UINT32_T, 0x06};

value_uint8 ublox_interval1_start = {0x0B, 11, 0, 23, 1, UINT8_T, 0x06};

value_uint8 ublox_min_fix_time = {0x0C, 5, 0, 30, 1, UINT8_T, 0x06};

value_bool ublox_multiple_intervals = {0x0D, false, false, true, 1, BOOL, 0x06};

value_bool ublox_active_tracking = {0x0E, false, false, true, 1, BOOL, 0x06};

value_uint32 gps_triggered_interval = {0x0F, 60, 0, 86400, 4, UINT32_T, 0x06};

value_uint8 gps_skipped_triggered_interval = {0x10, 5, 0, 255, 1, UINT8_T, 0x06};

value_uint8 ublox_leave_on = {0x11, 15, 0, 60, 1, UINT8_T, 0x06};

value_uint8 gnss_constellation_to_use = {0x12, 3, 1, 3, 1, UINT8_T, 0x06};

value_uint8 ublox_min_satellites_timer = {0x13, 30, 5, 255, 1, UINT8_T, 0x06};

value_uint8 ublox_interval2_start = {0x14, 19, 0, 23, 1, UINT8_T, 0x06};

value_uint8 ublox_min_satellites = {0x15, 3, 0, 255, 1, UINT8_T, 0x06};

value_uint8 gps_motion_triggered_min_num_of_triggers_per_interval = {0x16, 0,       0,   255,
								     1,    UINT8_T, 0x06};

value_bool enable_motion_trig_gps = {0x17, false, false, true, 1, BOOL, 0x06};

value_uint16 ublox_cold_fix_hour_interval = {0x18, 0, 0, 4320, 2, UINT16_T, 0x06};

value_uint32 satellite_send_interval = {0x00, 86400, 0, 86400, 4, UINT32_T, 0x07};

value_bool satellite_enabled = {0x01, false, false, true, 1, BOOL, 0x07};

value_uint8 satellite_retry = {0x02, 10, 1, 15, 1, UINT8_T, 0x07};

value_uint32 satellite_send_interval2 = {0x03, 86400, 0, 86400, 4, UINT32_T, 0x07};

value_uint8 satellite_send_interval2_start = {0x04, 19, 0, 23, 1, UINT8_T, 0x07};

value_bool satellite_multiple_intervals = {0x05, false, false, true, 1, BOOL, 0x07};

value_uint8 satellite_interval1_start = {0x06, 7, 0, 23, 1, UINT8_T, 0x07};

value_uint8 motion_ths = {0x00, 6, 0, 63, 1, UINT8_T, 0x08};

value_bool fence_enabled = {0x01, false, false, true, 1, BOOL, 0x08};

value_uint32 fence_interval = {0x02, 60, 0, 604800, 4, UINT32_T, 0x08};

value_uint16 fence_sampling_length = {0x03, 10, 1, 60, 2, UINT16_T, 0x08};

value_uint32 fence_mv_scaling_factor = {0x04, 100000, 100, 1000000, 4, UINT32_T, 0x08};

value_bool external_switch_detection_gpio_pin_power_enabled = {0x05, false, false, true,
							       1,    BOOL,  0x08};

value_bool fence_led_blink = {0x06, false, false, true, 1, BOOL, 0x08};

value_bool accel_movement_data_fifo_enabled = {0x07, false, false, true, 1, BOOL, 0x08};

value_uint16 accel_odr_hz = {0x08, 12, 0, 1600, 2, UINT16_T, 0x08};

value_uint8 accel_g_scale = {0x09, 2, 2, 16, 1, UINT8_T, 0x08};

value_bool outdoor_detection_enabled = {0x0A, false, false, true, 1, BOOL, 0x08};

value_uint8 outdoor_detection_tau = {0x0B, 11, 0, 100, 1, UINT8_T, 0x08};

uint8_t outdoor_detection_parameters_def[12] = {0xCB, 0xEC, 0x6B, 0x12, 0x2A, 0x13,
						0x79, 0x0F, 0x20, 0x1C, 0x00, 0x00};
uint8_t outdoor_detection_parameters_min[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
uint8_t outdoor_detection_parameters_max[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
						0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

value_byte_array outdoor_detection_parameters = {0x0C,
						 outdoor_detection_parameters_def,
						 outdoor_detection_parameters_min,
						 outdoor_detection_parameters_max,
						 12,
						 BYTE_ARRAY,
						 0x08};

value_bool external_switch_detection_enabled = {0x0E, false, false, true, 1, BOOL, 0x08};

value_uint8 external_switch_detection_trigger_type = {0x0F, 0, 0, 1, 1, UINT8_T, 0x08};

value_uint16 external_switch_detection_trigger_debounce_ms = {0x10, 50, 0, 2000, 2, UINT16_T, 0x08};

value_uint32 external_switch_detection_reporting_interval = {0x11, 3600,     0,   86400,
							     4,    UINT32_T, 0x08};

value_bool external_switch_send_inactivity_report = {0x12, true, false, true, 1, BOOL, 0x08};

value_uint16 external_switch_minimal_report_duration_ms = {0x13, 250, 0, 65000, 2, UINT16_T, 0x08};

value_uint8 external_switch_input_pull = {0x14, 1, 0, 2, 1, UINT8_T, 0x08};

value_bool external_switch_counter_enabled = {0x15, false, false, true, 1, BOOL, 0x08};

value_bool air_quality_enabled = {0x16, false, false, true, 1, BOOL, 0x08};

value_uint32 air_quality_interval = {0x17, 300, 10, 86400, 4, UINT32_T, 0x08};

uint8_t id_array[] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C,
		      0x00, 0x01, 0x02, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
		      0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
		      0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13,
		      0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20,
		      0x21, 0x22, 0x23, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
		      0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16,
		      0x17, 0x18, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x00, 0x01, 0x02, 0x03,
		      0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0E, 0x0F, 0x10, 0x11,
		      0x12, 0x13, 0x14, 0x15, 0x16, 0x17};
uint8_t family_array[] = {
	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x03,
	0x03, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04,
	0x04, 0x04, 0x04, 0x04, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
	0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
	0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x06, 0x06,
	0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06,
	0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x07, 0x07, 0x07, 0x07, 0x07,
	0x07, 0x07, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
	0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08};

uint8_t len_array[] = {1, 4, 4, 1, 4,  4,  8, 4,  1, 4, 4, 4, 1, 4, 4, 4,  1, 4, 4, 4, 4,
		       1, 4, 1, 1, 4,  4,  4, 6,  4, 1, 2, 4, 1, 1, 1, 16, 8, 8, 4, 4, 4,
		       2, 4, 1, 4, 16, 16, 4, 4,  1, 1, 4, 4, 1, 1, 1, 1,  2, 1, 4, 2, 1,
		       4, 4, 4, 4, 5,  4,  4, 4,  4, 4, 1, 1, 2, 2, 1, 4,  1, 1, 1, 1, 4,
		       1, 1, 1, 1, 1,  1,  1, 1,  2, 4, 1, 1, 4, 1, 1, 1,  1, 1, 4, 2, 4,
		       1, 1, 1, 2, 1,  1,  1, 12, 1, 1, 2, 4, 1, 2, 1, 1,  1, 4};

main_settings Main_settings = {&tracker_type,
			       &status_send_interval,
			       &init_time,
			       &data_log,
			       &wifi_scan_interval,
			       &wifi_scan_aggregated_interval,
			       &device_name,
			       &device_pin,
			       &led_enabled,
			       &memfault_send_interval,
			       &check_error_interval,
			       &flash_status_interval,
			       &wifi_scan_report_zero_connections_found,
			       &lr_send_flag,
			       &flash_store_flag,
			       &sat_send_flag,
			       &ble_adv,
			       &ble_advertisement_interval,
			       &ble_scan_duration,
			       &ble_scan_interval,
			       &ble_scan_aggregated_interval,
			       &ble_scan_filter,
			       &ble_auto_disconnect,
			       &ble_scan_report_zero_connections_found,
			       &cmdq_enabled,
			       &cmdq_scan_duration,
			       &cmdq_search_interval,
			       &cmdq_on_no_detection_wait_duration,
			       &cmdq_searched_mac_address,
			       &cmdq_reporting_interval,
			       &cmdq_report_zero_messages_to_be_sent,
			       &ble_scan_manufacturer_id,
			       &lr_gps_interval,
			       &gnss_assisted_scan,
			       &lr_adr,
			       &lr_region,
			       &app_key,
			       &device_eui,
			       &app_eui,
			       &s_band_send_interval,
			       &lr_join_flag,
			       &lr_confirm_flag,
			       &lr_max_confirm_fail,
			       &lr_messaging_retry_interval,
			       &lr_messaging_retry_count,
			       &rejoin_interval,
			       &lp0_app_key,
			       &lp0_network_key,
			       &lp0_dev_addr,
			       &s_band_rf_frequency_hz,
			       &lr_adr_profile,
			       &vhf_enabled,
			       &vhf_interval1,
			       &vhf_interval2,
			       &vhf_interval1_start,
			       &vhf_interval2_start,
			       &vhf_multiple_intervals,
			       &vhf_num_of_packets_per_burst,
			       &vhf_time_between_packets_ms,
			       &vhf_external_path,
			       &vhf_tx_frequency_khz,
			       &vhf_single_pulse_duration_ms,
			       &s_band_send_mode,
			       &lp0_send_flag,
			       &lp0_tx_frequency_hz,
			       &lp0_rx_frequency_hz,
			       &lp0_communication_params,
			       &lp0_node_params,
			       &ublox_send_interval,
			       &gps_init_lon,
			       &gps_init_lat,
			       &gps_resend_interval,
			       &horizontal_accuracy,
			       &cold_fix_retry,
			       &hot_fix_retry,
			       &cold_fix_timeout,
			       &hot_fix_timeout,
			       &gps_backoff_factor,
			       &ublox_send_interval_2,
			       &ublox_interval1_start,
			       &ublox_min_fix_time,
			       &ublox_multiple_intervals,
			       &ublox_active_tracking,
			       &gps_triggered_interval,
			       &gps_skipped_triggered_interval,
			       &ublox_leave_on,
			       &gnss_constellation_to_use,
			       &ublox_min_satellites_timer,
			       &ublox_interval2_start,
			       &ublox_min_satellites,
			       &gps_motion_triggered_min_num_of_triggers_per_interval,
			       &enable_motion_trig_gps,
			       &ublox_cold_fix_hour_interval,
			       &satellite_send_interval,
			       &satellite_enabled,
			       &satellite_retry,
			       &satellite_send_interval2,
			       &satellite_send_interval2_start,
			       &satellite_multiple_intervals,
			       &satellite_interval1_start,
			       &motion_ths,
			       &fence_enabled,
			       &fence_interval,
			       &fence_sampling_length,
			       &fence_mv_scaling_factor,
			       &external_switch_detection_gpio_pin_power_enabled,
			       &fence_led_blink,
			       &accel_movement_data_fifo_enabled,
			       &accel_odr_hz,
			       &accel_g_scale,
			       &outdoor_detection_enabled,
			       &outdoor_detection_tau,
			       &outdoor_detection_parameters,
			       &external_switch_detection_enabled,
			       &external_switch_detection_trigger_type,
			       &external_switch_detection_trigger_debounce_ms,
			       &external_switch_detection_reporting_interval,
			       &external_switch_send_inactivity_report,
			       &external_switch_minimal_report_duration_ms,
			       &external_switch_input_pull,
			       &external_switch_counter_enabled,
			       &air_quality_enabled,
			       &air_quality_interval,
			       123,
			       id_array,
			       family_array,
			       len_array};

void *get_setting_struct_by_id(uint8_t family, uint8_t id)
{
	switch (MAKE_KEY(family, id)) {
	case MAKE_KEY(0x02, 0x00):
		return Main_settings.tracker_type;
	case MAKE_KEY(0x02, 0x01):
		return Main_settings.status_send_interval;
	case MAKE_KEY(0x02, 0x02):
		return Main_settings.init_time;
	case MAKE_KEY(0x02, 0x03):
		return Main_settings.data_log;
	case MAKE_KEY(0x02, 0x04):
		return Main_settings.wifi_scan_interval;
	case MAKE_KEY(0x02, 0x05):
		return Main_settings.wifi_scan_aggregated_interval;
	case MAKE_KEY(0x02, 0x06):
		return Main_settings.device_name;
	case MAKE_KEY(0x02, 0x07):
		return Main_settings.device_pin;
	case MAKE_KEY(0x02, 0x08):
		return Main_settings.led_enabled;
	case MAKE_KEY(0x02, 0x09):
		return Main_settings.memfault_send_interval;
	case MAKE_KEY(0x02, 0x0A):
		return Main_settings.check_error_interval;
	case MAKE_KEY(0x02, 0x0B):
		return Main_settings.flash_status_interval;
	case MAKE_KEY(0x02, 0x0C):
		return Main_settings.wifi_scan_report_zero_connections_found;
	case MAKE_KEY(0x03, 0x00):
		return Main_settings.lr_send_flag;
	case MAKE_KEY(0x03, 0x01):
		return Main_settings.flash_store_flag;
	case MAKE_KEY(0x03, 0x02):
		return Main_settings.sat_send_flag;
	case MAKE_KEY(0x04, 0x00):
		return Main_settings.ble_adv;
	case MAKE_KEY(0x04, 0x01):
		return Main_settings.ble_advertisement_interval;
	case MAKE_KEY(0x04, 0x02):
		return Main_settings.ble_scan_duration;
	case MAKE_KEY(0x04, 0x03):
		return Main_settings.ble_scan_interval;
	case MAKE_KEY(0x04, 0x04):
		return Main_settings.ble_scan_aggregated_interval;
	case MAKE_KEY(0x04, 0x05):
		return Main_settings.ble_scan_filter;
	case MAKE_KEY(0x04, 0x06):
		return Main_settings.ble_auto_disconnect;
	case MAKE_KEY(0x04, 0x07):
		return Main_settings.ble_scan_report_zero_connections_found;
	case MAKE_KEY(0x04, 0x08):
		return Main_settings.cmdq_enabled;
	case MAKE_KEY(0x04, 0x09):
		return Main_settings.cmdq_scan_duration;
	case MAKE_KEY(0x04, 0x0A):
		return Main_settings.cmdq_search_interval;
	case MAKE_KEY(0x04, 0x0B):
		return Main_settings.cmdq_on_no_detection_wait_duration;
	case MAKE_KEY(0x04, 0x0C):
		return Main_settings.cmdq_searched_mac_address;
	case MAKE_KEY(0x04, 0x0D):
		return Main_settings.cmdq_reporting_interval;
	case MAKE_KEY(0x04, 0x0E):
		return Main_settings.cmdq_report_zero_messages_to_be_sent;
	case MAKE_KEY(0x04, 0x0F):
		return Main_settings.ble_scan_manufacturer_id;
	case MAKE_KEY(0x05, 0x00):
		return Main_settings.lr_gps_interval;
	case MAKE_KEY(0x05, 0x01):
		return Main_settings.gnss_assisted_scan;
	case MAKE_KEY(0x05, 0x02):
		return Main_settings.lr_adr;
	case MAKE_KEY(0x05, 0x03):
		return Main_settings.lr_region;
	case MAKE_KEY(0x05, 0x04):
		return Main_settings.app_key;
	case MAKE_KEY(0x05, 0x05):
		return Main_settings.device_eui;
	case MAKE_KEY(0x05, 0x06):
		return Main_settings.app_eui;
	case MAKE_KEY(0x05, 0x07):
		return Main_settings.s_band_send_interval;
	case MAKE_KEY(0x05, 0x08):
		return Main_settings.lr_join_flag;
	case MAKE_KEY(0x05, 0x09):
		return Main_settings.lr_confirm_flag;
	case MAKE_KEY(0x05, 0x0A):
		return Main_settings.lr_max_confirm_fail;
	case MAKE_KEY(0x05, 0x0B):
		return Main_settings.lr_messaging_retry_interval;
	case MAKE_KEY(0x05, 0x0C):
		return Main_settings.lr_messaging_retry_count;
	case MAKE_KEY(0x05, 0x0D):
		return Main_settings.rejoin_interval;
	case MAKE_KEY(0x05, 0x0E):
		return Main_settings.lp0_app_key;
	case MAKE_KEY(0x05, 0x0F):
		return Main_settings.lp0_network_key;
	case MAKE_KEY(0x05, 0x10):
		return Main_settings.lp0_dev_addr;
	case MAKE_KEY(0x05, 0x11):
		return Main_settings.s_band_rf_frequency_hz;
	case MAKE_KEY(0x05, 0x12):
		return Main_settings.lr_adr_profile;
	case MAKE_KEY(0x05, 0x13):
		return Main_settings.vhf_enabled;
	case MAKE_KEY(0x05, 0x14):
		return Main_settings.vhf_interval1;
	case MAKE_KEY(0x05, 0x15):
		return Main_settings.vhf_interval2;
	case MAKE_KEY(0x05, 0x16):
		return Main_settings.vhf_interval1_start;
	case MAKE_KEY(0x05, 0x17):
		return Main_settings.vhf_interval2_start;
	case MAKE_KEY(0x05, 0x18):
		return Main_settings.vhf_multiple_intervals;
	case MAKE_KEY(0x05, 0x19):
		return Main_settings.vhf_num_of_packets_per_burst;
	case MAKE_KEY(0x05, 0x1A):
		return Main_settings.vhf_time_between_packets_ms;
	case MAKE_KEY(0x05, 0x1B):
		return Main_settings.vhf_external_path;
	case MAKE_KEY(0x05, 0x1C):
		return Main_settings.vhf_tx_frequency_khz;
	case MAKE_KEY(0x05, 0x1D):
		return Main_settings.vhf_single_pulse_duration_ms;
	case MAKE_KEY(0x05, 0x1E):
		return Main_settings.s_band_send_mode;
	case MAKE_KEY(0x05, 0x1F):
		return Main_settings.lp0_send_flag;
	case MAKE_KEY(0x05, 0x20):
		return Main_settings.lp0_tx_frequency_hz;
	case MAKE_KEY(0x05, 0x21):
		return Main_settings.lp0_rx_frequency_hz;
	case MAKE_KEY(0x05, 0x22):
		return Main_settings.lp0_communication_params;
	case MAKE_KEY(0x05, 0x23):
		return Main_settings.lp0_node_params;
	case MAKE_KEY(0x06, 0x00):
		return Main_settings.ublox_send_interval;
	case MAKE_KEY(0x06, 0x01):
		return Main_settings.gps_init_lon;
	case MAKE_KEY(0x06, 0x02):
		return Main_settings.gps_init_lat;
	case MAKE_KEY(0x06, 0x03):
		return Main_settings.gps_resend_interval;
	case MAKE_KEY(0x06, 0x04):
		return Main_settings.horizontal_accuracy;
	case MAKE_KEY(0x06, 0x05):
		return Main_settings.cold_fix_retry;
	case MAKE_KEY(0x06, 0x06):
		return Main_settings.hot_fix_retry;
	case MAKE_KEY(0x06, 0x07):
		return Main_settings.cold_fix_timeout;
	case MAKE_KEY(0x06, 0x08):
		return Main_settings.hot_fix_timeout;
	case MAKE_KEY(0x06, 0x09):
		return Main_settings.gps_backoff_factor;
	case MAKE_KEY(0x06, 0x0A):
		return Main_settings.ublox_send_interval_2;
	case MAKE_KEY(0x06, 0x0B):
		return Main_settings.ublox_interval1_start;
	case MAKE_KEY(0x06, 0x0C):
		return Main_settings.ublox_min_fix_time;
	case MAKE_KEY(0x06, 0x0D):
		return Main_settings.ublox_multiple_intervals;
	case MAKE_KEY(0x06, 0x0E):
		return Main_settings.ublox_active_tracking;
	case MAKE_KEY(0x06, 0x0F):
		return Main_settings.gps_triggered_interval;
	case MAKE_KEY(0x06, 0x10):
		return Main_settings.gps_skipped_triggered_interval;
	case MAKE_KEY(0x06, 0x11):
		return Main_settings.ublox_leave_on;
	case MAKE_KEY(0x06, 0x12):
		return Main_settings.gnss_constellation_to_use;
	case MAKE_KEY(0x06, 0x13):
		return Main_settings.ublox_min_satellites_timer;
	case MAKE_KEY(0x06, 0x14):
		return Main_settings.ublox_interval2_start;
	case MAKE_KEY(0x06, 0x15):
		return Main_settings.ublox_min_satellites;
	case MAKE_KEY(0x06, 0x16):
		return Main_settings.gps_motion_triggered_min_num_of_triggers_per_interval;
	case MAKE_KEY(0x06, 0x17):
		return Main_settings.enable_motion_trig_gps;
	case MAKE_KEY(0x06, 0x18):
		return Main_settings.ublox_cold_fix_hour_interval;
	case MAKE_KEY(0x07, 0x00):
		return Main_settings.satellite_send_interval;
	case MAKE_KEY(0x07, 0x01):
		return Main_settings.satellite_enabled;
	case MAKE_KEY(0x07, 0x02):
		return Main_settings.satellite_retry;
	case MAKE_KEY(0x07, 0x03):
		return Main_settings.satellite_send_interval2;
	case MAKE_KEY(0x07, 0x04):
		return Main_settings.satellite_send_interval2_start;
	case MAKE_KEY(0x07, 0x05):
		return Main_settings.satellite_multiple_intervals;
	case MAKE_KEY(0x07, 0x06):
		return Main_settings.satellite_interval1_start;
	case MAKE_KEY(0x08, 0x00):
		return Main_settings.motion_ths;
	case MAKE_KEY(0x08, 0x01):
		return Main_settings.fence_enabled;
	case MAKE_KEY(0x08, 0x02):
		return Main_settings.fence_interval;
	case MAKE_KEY(0x08, 0x03):
		return Main_settings.fence_sampling_length;
	case MAKE_KEY(0x08, 0x04):
		return Main_settings.fence_mv_scaling_factor;
	case MAKE_KEY(0x08, 0x05):
		return Main_settings.external_switch_detection_gpio_pin_power_enabled;
	case MAKE_KEY(0x08, 0x06):
		return Main_settings.fence_led_blink;
	case MAKE_KEY(0x08, 0x07):
		return Main_settings.accel_movement_data_fifo_enabled;
	case MAKE_KEY(0x08, 0x08):
		return Main_settings.accel_odr_hz;
	case MAKE_KEY(0x08, 0x09):
		return Main_settings.accel_g_scale;
	case MAKE_KEY(0x08, 0x0A):
		return Main_settings.outdoor_detection_enabled;
	case MAKE_KEY(0x08, 0x0B):
		return Main_settings.outdoor_detection_tau;
	case MAKE_KEY(0x08, 0x0C):
		return Main_settings.outdoor_detection_parameters;
	case MAKE_KEY(0x08, 0x0E):
		return Main_settings.external_switch_detection_enabled;
	case MAKE_KEY(0x08, 0x0F):
		return Main_settings.external_switch_detection_trigger_type;
	case MAKE_KEY(0x08, 0x10):
		return Main_settings.external_switch_detection_trigger_debounce_ms;
	case MAKE_KEY(0x08, 0x11):
		return Main_settings.external_switch_detection_reporting_interval;
	case MAKE_KEY(0x08, 0x12):
		return Main_settings.external_switch_send_inactivity_report;
	case MAKE_KEY(0x08, 0x13):
		return Main_settings.external_switch_minimal_report_duration_ms;
	case MAKE_KEY(0x08, 0x14):
		return Main_settings.external_switch_input_pull;
	case MAKE_KEY(0x08, 0x15):
		return Main_settings.external_switch_counter_enabled;
	case MAKE_KEY(0x08, 0x16):
		return Main_settings.air_quality_enabled;
	case MAKE_KEY(0x08, 0x17):
		return Main_settings.air_quality_interval;
	default:
		return NULL;
	}
}

int get_setting_by_id(uint8_t family, uint8_t id, uint8_t *bytes)
{
	switch (MAKE_KEY(family, id)) {
	case MAKE_KEY(0x02, 0x00):
		uint8_t_to_bytes(bytes, Main_settings.tracker_type->def_val);
		return 1;
	case MAKE_KEY(0x02, 0x01):
		uint32_t_to_bytes(bytes, Main_settings.status_send_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x02):
		uint32_t_to_bytes(bytes, Main_settings.init_time->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x03):
		bool_to_bytes(bytes, Main_settings.data_log->def_val);
		return 1;
	case MAKE_KEY(0x02, 0x04):
		uint32_t_to_bytes(bytes, Main_settings.wifi_scan_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x05):
		uint32_t_to_bytes(bytes, Main_settings.wifi_scan_aggregated_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x06):
		byte_array_to_bytes(bytes, Main_settings.device_name->def_val, 8);
		return 8;
	case MAKE_KEY(0x02, 0x07):
		byte_array_to_bytes(bytes, Main_settings.device_pin->def_val, 4);
		return 4;
	case MAKE_KEY(0x02, 0x08):
		bool_to_bytes(bytes, Main_settings.led_enabled->def_val);
		return 1;
	case MAKE_KEY(0x02, 0x09):
		uint32_t_to_bytes(bytes, Main_settings.memfault_send_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x0A):
		uint32_t_to_bytes(bytes, Main_settings.check_error_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x0B):
		uint32_t_to_bytes(bytes, Main_settings.flash_status_interval->def_val);
		return 4;
	case MAKE_KEY(0x02, 0x0C):
		bool_to_bytes(bytes,
			      Main_settings.wifi_scan_report_zero_connections_found->def_val);
		return 1;
	case MAKE_KEY(0x03, 0x00):
		uint32_t_to_bytes(bytes, Main_settings.lr_send_flag->def_val);
		return 4;
	case MAKE_KEY(0x03, 0x01):
		uint32_t_to_bytes(bytes, Main_settings.flash_store_flag->def_val);
		return 4;
	case MAKE_KEY(0x03, 0x02):
		uint32_t_to_bytes(bytes, Main_settings.sat_send_flag->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x00):
		bool_to_bytes(bytes, Main_settings.ble_adv->def_val);
		return 1;
	case MAKE_KEY(0x04, 0x01):
		uint32_t_to_bytes(bytes, Main_settings.ble_advertisement_interval->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x02):
		uint32_t_to_bytes(bytes, Main_settings.ble_scan_duration->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x03):
		uint32_t_to_bytes(bytes, Main_settings.ble_scan_interval->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x04):
		uint32_t_to_bytes(bytes, Main_settings.ble_scan_aggregated_interval->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x05):
		uint8_t_to_bytes(bytes, Main_settings.ble_scan_filter->def_val);
		return 1;
	case MAKE_KEY(0x04, 0x06):
		uint32_t_to_bytes(bytes, Main_settings.ble_auto_disconnect->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x07):
		bool_to_bytes(bytes, Main_settings.ble_scan_report_zero_connections_found->def_val);
		return 1;
	case MAKE_KEY(0x04, 0x08):
		bool_to_bytes(bytes, Main_settings.cmdq_enabled->def_val);
		return 1;
	case MAKE_KEY(0x04, 0x09):
		uint32_t_to_bytes(bytes, Main_settings.cmdq_scan_duration->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x0A):
		uint32_t_to_bytes(bytes, Main_settings.cmdq_search_interval->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x0B):
		uint32_t_to_bytes(bytes, Main_settings.cmdq_on_no_detection_wait_duration->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x0C):
		byte_array_to_bytes(bytes, Main_settings.cmdq_searched_mac_address->def_val, 6);
		return 6;
	case MAKE_KEY(0x04, 0x0D):
		uint32_t_to_bytes(bytes, Main_settings.cmdq_reporting_interval->def_val);
		return 4;
	case MAKE_KEY(0x04, 0x0E):
		bool_to_bytes(bytes, Main_settings.cmdq_report_zero_messages_to_be_sent->def_val);
		return 1;
	case MAKE_KEY(0x04, 0x0F):
		uint16_t_to_bytes(bytes, Main_settings.ble_scan_manufacturer_id->def_val);
		return 2;
	case MAKE_KEY(0x05, 0x00):
		uint32_t_to_bytes(bytes, Main_settings.lr_gps_interval->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x01):
		bool_to_bytes(bytes, Main_settings.gnss_assisted_scan->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x02):
		uint8_t_to_bytes(bytes, Main_settings.lr_adr->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x03):
		uint8_t_to_bytes(bytes, Main_settings.lr_region->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x04):
		byte_array_to_bytes(bytes, Main_settings.app_key->def_val, 16);
		return 16;
	case MAKE_KEY(0x05, 0x05):
		byte_array_to_bytes(bytes, Main_settings.device_eui->def_val, 8);
		return 8;
	case MAKE_KEY(0x05, 0x06):
		byte_array_to_bytes(bytes, Main_settings.app_eui->def_val, 8);
		return 8;
	case MAKE_KEY(0x05, 0x07):
		uint32_t_to_bytes(bytes, Main_settings.s_band_send_interval->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x08):
		uint32_t_to_bytes(bytes, Main_settings.lr_join_flag->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x09):
		uint32_t_to_bytes(bytes, Main_settings.lr_confirm_flag->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x0A):
		uint16_t_to_bytes(bytes, Main_settings.lr_max_confirm_fail->def_val);
		return 2;
	case MAKE_KEY(0x05, 0x0B):
		uint32_t_to_bytes(bytes, Main_settings.lr_messaging_retry_interval->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x0C):
		uint8_t_to_bytes(bytes, Main_settings.lr_messaging_retry_count->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x0D):
		uint32_t_to_bytes(bytes, Main_settings.rejoin_interval->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x0E):
		byte_array_to_bytes(bytes, Main_settings.lp0_app_key->def_val, 16);
		return 16;
	case MAKE_KEY(0x05, 0x0F):
		byte_array_to_bytes(bytes, Main_settings.lp0_network_key->def_val, 16);
		return 16;
	case MAKE_KEY(0x05, 0x10):
		byte_array_to_bytes(bytes, Main_settings.lp0_dev_addr->def_val, 4);
		return 4;
	case MAKE_KEY(0x05, 0x11):
		uint32_t_to_bytes(bytes, Main_settings.s_band_rf_frequency_hz->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x12):
		uint8_t_to_bytes(bytes, Main_settings.lr_adr_profile->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x13):
		bool_to_bytes(bytes, Main_settings.vhf_enabled->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x14):
		uint32_t_to_bytes(bytes, Main_settings.vhf_interval1->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x15):
		uint32_t_to_bytes(bytes, Main_settings.vhf_interval2->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x16):
		uint8_t_to_bytes(bytes, Main_settings.vhf_interval1_start->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x17):
		uint8_t_to_bytes(bytes, Main_settings.vhf_interval2_start->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x18):
		bool_to_bytes(bytes, Main_settings.vhf_multiple_intervals->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x19):
		uint8_t_to_bytes(bytes, Main_settings.vhf_num_of_packets_per_burst->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x1A):
		uint16_t_to_bytes(bytes, Main_settings.vhf_time_between_packets_ms->def_val);
		return 2;
	case MAKE_KEY(0x05, 0x1B):
		bool_to_bytes(bytes, Main_settings.vhf_external_path->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x1C):
		uint32_t_to_bytes(bytes, Main_settings.vhf_tx_frequency_khz->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x1D):
		uint16_t_to_bytes(bytes, Main_settings.vhf_single_pulse_duration_ms->def_val);
		return 2;
	case MAKE_KEY(0x05, 0x1E):
		uint8_t_to_bytes(bytes, Main_settings.s_band_send_mode->def_val);
		return 1;
	case MAKE_KEY(0x05, 0x1F):
		uint32_t_to_bytes(bytes, Main_settings.lp0_send_flag->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x20):
		uint32_t_to_bytes(bytes, Main_settings.lp0_tx_frequency_hz->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x21):
		uint32_t_to_bytes(bytes, Main_settings.lp0_rx_frequency_hz->def_val);
		return 4;
	case MAKE_KEY(0x05, 0x22):
		byte_array_to_bytes(bytes, Main_settings.lp0_communication_params->def_val, 4);
		return 4;
	case MAKE_KEY(0x05, 0x23):
		byte_array_to_bytes(bytes, Main_settings.lp0_node_params->def_val, 5);
		return 5;
	case MAKE_KEY(0x06, 0x00):
		uint32_t_to_bytes(bytes, Main_settings.ublox_send_interval->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x01):
		int32_t_to_bytes(bytes, Main_settings.gps_init_lon->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x02):
		int32_t_to_bytes(bytes, Main_settings.gps_init_lat->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x03):
		uint32_t_to_bytes(bytes, Main_settings.gps_resend_interval->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x04):
		uint32_t_to_bytes(bytes, Main_settings.horizontal_accuracy->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x05):
		uint8_t_to_bytes(bytes, Main_settings.cold_fix_retry->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x06):
		uint8_t_to_bytes(bytes, Main_settings.hot_fix_retry->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x07):
		uint16_t_to_bytes(bytes, Main_settings.cold_fix_timeout->def_val);
		return 2;
	case MAKE_KEY(0x06, 0x08):
		uint16_t_to_bytes(bytes, Main_settings.hot_fix_timeout->def_val);
		return 2;
	case MAKE_KEY(0x06, 0x09):
		uint8_t_to_bytes(bytes, Main_settings.gps_backoff_factor->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x0A):
		uint32_t_to_bytes(bytes, Main_settings.ublox_send_interval_2->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x0B):
		uint8_t_to_bytes(bytes, Main_settings.ublox_interval1_start->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x0C):
		uint8_t_to_bytes(bytes, Main_settings.ublox_min_fix_time->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x0D):
		bool_to_bytes(bytes, Main_settings.ublox_multiple_intervals->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x0E):
		bool_to_bytes(bytes, Main_settings.ublox_active_tracking->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x0F):
		uint32_t_to_bytes(bytes, Main_settings.gps_triggered_interval->def_val);
		return 4;
	case MAKE_KEY(0x06, 0x10):
		uint8_t_to_bytes(bytes, Main_settings.gps_skipped_triggered_interval->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x11):
		uint8_t_to_bytes(bytes, Main_settings.ublox_leave_on->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x12):
		uint8_t_to_bytes(bytes, Main_settings.gnss_constellation_to_use->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x13):
		uint8_t_to_bytes(bytes, Main_settings.ublox_min_satellites_timer->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x14):
		uint8_t_to_bytes(bytes, Main_settings.ublox_interval2_start->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x15):
		uint8_t_to_bytes(bytes, Main_settings.ublox_min_satellites->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x16):
		uint8_t_to_bytes(
			bytes, Main_settings.gps_motion_triggered_min_num_of_triggers_per_interval
				       ->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x17):
		bool_to_bytes(bytes, Main_settings.enable_motion_trig_gps->def_val);
		return 1;
	case MAKE_KEY(0x06, 0x18):
		uint16_t_to_bytes(bytes, Main_settings.ublox_cold_fix_hour_interval->def_val);
		return 2;
	case MAKE_KEY(0x07, 0x00):
		uint32_t_to_bytes(bytes, Main_settings.satellite_send_interval->def_val);
		return 4;
	case MAKE_KEY(0x07, 0x01):
		bool_to_bytes(bytes, Main_settings.satellite_enabled->def_val);
		return 1;
	case MAKE_KEY(0x07, 0x02):
		uint8_t_to_bytes(bytes, Main_settings.satellite_retry->def_val);
		return 1;
	case MAKE_KEY(0x07, 0x03):
		uint32_t_to_bytes(bytes, Main_settings.satellite_send_interval2->def_val);
		return 4;
	case MAKE_KEY(0x07, 0x04):
		uint8_t_to_bytes(bytes, Main_settings.satellite_send_interval2_start->def_val);
		return 1;
	case MAKE_KEY(0x07, 0x05):
		bool_to_bytes(bytes, Main_settings.satellite_multiple_intervals->def_val);
		return 1;
	case MAKE_KEY(0x07, 0x06):
		uint8_t_to_bytes(bytes, Main_settings.satellite_interval1_start->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x00):
		uint8_t_to_bytes(bytes, Main_settings.motion_ths->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x01):
		bool_to_bytes(bytes, Main_settings.fence_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x02):
		uint32_t_to_bytes(bytes, Main_settings.fence_interval->def_val);
		return 4;
	case MAKE_KEY(0x08, 0x03):
		uint16_t_to_bytes(bytes, Main_settings.fence_sampling_length->def_val);
		return 2;
	case MAKE_KEY(0x08, 0x04):
		uint32_t_to_bytes(bytes, Main_settings.fence_mv_scaling_factor->def_val);
		return 4;
	case MAKE_KEY(0x08, 0x05):
		bool_to_bytes(
			bytes,
			Main_settings.external_switch_detection_gpio_pin_power_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x06):
		bool_to_bytes(bytes, Main_settings.fence_led_blink->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x07):
		bool_to_bytes(bytes, Main_settings.accel_movement_data_fifo_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x08):
		uint16_t_to_bytes(bytes, Main_settings.accel_odr_hz->def_val);
		return 2;
	case MAKE_KEY(0x08, 0x09):
		uint8_t_to_bytes(bytes, Main_settings.accel_g_scale->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x0A):
		bool_to_bytes(bytes, Main_settings.outdoor_detection_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x0B):
		uint8_t_to_bytes(bytes, Main_settings.outdoor_detection_tau->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x0C):
		byte_array_to_bytes(bytes, Main_settings.outdoor_detection_parameters->def_val, 12);
		return 12;
	case MAKE_KEY(0x08, 0x0E):
		bool_to_bytes(bytes, Main_settings.external_switch_detection_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x0F):
		uint8_t_to_bytes(bytes,
				 Main_settings.external_switch_detection_trigger_type->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x10):
		uint16_t_to_bytes(
			bytes,
			Main_settings.external_switch_detection_trigger_debounce_ms->def_val);
		return 2;
	case MAKE_KEY(0x08, 0x11):
		uint32_t_to_bytes(
			bytes, Main_settings.external_switch_detection_reporting_interval->def_val);
		return 4;
	case MAKE_KEY(0x08, 0x12):
		bool_to_bytes(bytes, Main_settings.external_switch_send_inactivity_report->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x13):
		uint16_t_to_bytes(
			bytes, Main_settings.external_switch_minimal_report_duration_ms->def_val);
		return 2;
	case MAKE_KEY(0x08, 0x14):
		uint8_t_to_bytes(bytes, Main_settings.external_switch_input_pull->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x15):
		bool_to_bytes(bytes, Main_settings.external_switch_counter_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x16):
		bool_to_bytes(bytes, Main_settings.air_quality_enabled->def_val);
		return 1;
	case MAKE_KEY(0x08, 0x17):
		uint32_t_to_bytes(bytes, Main_settings.air_quality_interval->def_val);
		return 4;
	default:
		return 0;
	}
}

static int setting_default_uint8_to_bytes(uint8_t value, uint8_t *bytes, uint8_t len)
{
	if (len != 1) {
		return 0;
	}
	bytes[0] = value;
	return 1;
}

static int setting_default_uint16_to_bytes(uint16_t value, uint8_t *bytes, uint8_t len)
{
	if (len != 2) {
		return 0;
	}
	sys_put_le16(value, bytes);
	return 2;
}

static int setting_default_uint32_to_bytes(uint32_t value, uint8_t *bytes, uint8_t len)
{
	if (len != 4) {
		return 0;
	}
	sys_put_le32(value, bytes);
	return 4;
}

int get_setting_default_by_id(uint8_t family, uint8_t id, uint8_t *bytes, uint8_t len)
{
	if (bytes == NULL) {
		return 0;
	}
	switch (MAKE_KEY(family, id)) {
	case MAKE_KEY(0x02, 0x00):
		return setting_default_uint8_to_bytes((uint8_t)(0), bytes, len);
	case MAKE_KEY(0x02, 0x01):
		return setting_default_uint32_to_bytes((uint32_t)(3600), bytes, len);
	case MAKE_KEY(0x02, 0x02):
		return setting_default_uint32_to_bytes((uint32_t)(1787788800), bytes, len);
	case MAKE_KEY(0x02, 0x03):
		return setting_default_uint8_to_bytes((uint8_t)(true), bytes, len);
	case MAKE_KEY(0x02, 0x04):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x02, 0x05):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x02, 0x06): {
		if (len != 8) {
			return 0;
		}
		static const uint8_t default_value[8] = "";
		memcpy(bytes, default_value, sizeof(default_value));
		return 8;
	}
	case MAKE_KEY(0x02, 0x07): {
		if (len != 4) {
			return 0;
		}
		static const uint8_t default_value[4] = {0x00, 0x00, 0x00, 0x00};
		memcpy(bytes, default_value, sizeof(default_value));
		return 4;
	}
	case MAKE_KEY(0x02, 0x08):
		return setting_default_uint8_to_bytes((uint8_t)(true), bytes, len);
	case MAKE_KEY(0x02, 0x09):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x02, 0x0A):
		return setting_default_uint32_to_bytes((uint32_t)(86400), bytes, len);
	case MAKE_KEY(0x02, 0x0B):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x02, 0x0C):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x03, 0x00):
		return setting_default_uint32_to_bytes((uint32_t)(4162715375), bytes, len);
	case MAKE_KEY(0x03, 0x01):
		return setting_default_uint32_to_bytes((uint32_t)(876143), bytes, len);
	case MAKE_KEY(0x03, 0x02):
		return setting_default_uint32_to_bytes((uint32_t)(16522), bytes, len);
	case MAKE_KEY(0x04, 0x00):
		return setting_default_uint8_to_bytes((uint8_t)(true), bytes, len);
	case MAKE_KEY(0x04, 0x01):
		return setting_default_uint32_to_bytes((uint32_t)(500), bytes, len);
	case MAKE_KEY(0x04, 0x02):
		return setting_default_uint32_to_bytes((uint32_t)(600), bytes, len);
	case MAKE_KEY(0x04, 0x03):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x04, 0x04):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x04, 0x05):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x04, 0x06):
		return setting_default_uint32_to_bytes((uint32_t)(600), bytes, len);
	case MAKE_KEY(0x04, 0x07):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x04, 0x08):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x04, 0x09):
		return setting_default_uint32_to_bytes((uint32_t)(10000), bytes, len);
	case MAKE_KEY(0x04, 0x0A):
		return setting_default_uint32_to_bytes((uint32_t)(300), bytes, len);
	case MAKE_KEY(0x04, 0x0B):
		return setting_default_uint32_to_bytes((uint32_t)(1800), bytes, len);
	case MAKE_KEY(0x04, 0x0C): {
		if (len != 6) {
			return 0;
		}
		static const uint8_t default_value[6] = {0xD8, 0x10, 0x68, 0xAC, 0xDA, 0xE4};
		memcpy(bytes, default_value, sizeof(default_value));
		return 6;
	}
	case MAKE_KEY(0x04, 0x0D):
		return setting_default_uint32_to_bytes((uint32_t)(300), bytes, len);
	case MAKE_KEY(0x04, 0x0E):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x04, 0x0F):
		return setting_default_uint16_to_bytes((uint16_t)(2657), bytes, len);
	case MAKE_KEY(0x05, 0x00):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x01):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x05, 0x02):
		return setting_default_uint8_to_bytes((uint8_t)(3), bytes, len);
	case MAKE_KEY(0x05, 0x03):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x05, 0x04): {
		if (len != 16) {
			return 0;
		}
		static const uint8_t default_value[16] = {0x8B, 0xCD, 0x49, 0x42, 0x11, 0x67,
							  0xDD, 0x03, 0xBA, 0xD3, 0xAE, 0xEA,
							  0x98, 0xEF, 0xE4, 0x09};
		memcpy(bytes, default_value, sizeof(default_value));
		return 16;
	}
	case MAKE_KEY(0x05, 0x05): {
		if (len != 8) {
			return 0;
		}
		static const uint8_t default_value[8] = {0x00, 0x00, 0x00, 0x00,
							 0x00, 0x00, 0x00, 0x00};
		memcpy(bytes, default_value, sizeof(default_value));
		return 8;
	}
	case MAKE_KEY(0x05, 0x06): {
		if (len != 8) {
			return 0;
		}
		static const uint8_t default_value[8] = {0x00, 0x00, 0x00, 0x00,
							 0x00, 0x00, 0x00, 0x00};
		memcpy(bytes, default_value, sizeof(default_value));
		return 8;
	}
	case MAKE_KEY(0x05, 0x07):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x08):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x09):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x0A):
		return setting_default_uint16_to_bytes((uint16_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x0B):
		return setting_default_uint32_to_bytes((uint32_t)(60), bytes, len);
	case MAKE_KEY(0x05, 0x0C):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x05, 0x0D):
		return setting_default_uint32_to_bytes((uint32_t)(3600), bytes, len);
	case MAKE_KEY(0x05, 0x0E): {
		if (len != 16) {
			return 0;
		}
		static const uint8_t default_value[16] = {0xEC, 0x7F, 0x38, 0x0E, 0x7A, 0xDF,
							  0xB2, 0xE5, 0xC9, 0xBB, 0xDE, 0x5A,
							  0xC2, 0x16, 0x94, 0xA8};
		memcpy(bytes, default_value, sizeof(default_value));
		return 16;
	}
	case MAKE_KEY(0x05, 0x0F): {
		if (len != 16) {
			return 0;
		}
		static const uint8_t default_value[16] = {0xDB, 0x7E, 0x27, 0x26, 0xCF, 0xF5,
							  0x8C, 0x13, 0x3A, 0x07, 0xB5, 0xA1,
							  0xB4, 0x00, 0xE1, 0xD0};
		memcpy(bytes, default_value, sizeof(default_value));
		return 16;
	}
	case MAKE_KEY(0x05, 0x10): {
		if (len != 4) {
			return 0;
		}
		static const uint8_t default_value[4] = {0x26, 0x0B, 0xF6, 0xEF};
		memcpy(bytes, default_value, sizeof(default_value));
		return 4;
	}
	case MAKE_KEY(0x05, 0x11):
		return setting_default_uint32_to_bytes((uint32_t)(2008450000), bytes, len);
	case MAKE_KEY(0x05, 0x12):
		return setting_default_uint8_to_bytes((uint8_t)(3), bytes, len);
	case MAKE_KEY(0x05, 0x13):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x05, 0x14):
		return setting_default_uint32_to_bytes((uint32_t)(2), bytes, len);
	case MAKE_KEY(0x05, 0x15):
		return setting_default_uint32_to_bytes((uint32_t)(2), bytes, len);
	case MAKE_KEY(0x05, 0x16):
		return setting_default_uint8_to_bytes((uint8_t)(7), bytes, len);
	case MAKE_KEY(0x05, 0x17):
		return setting_default_uint8_to_bytes((uint8_t)(19), bytes, len);
	case MAKE_KEY(0x05, 0x18):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x05, 0x19):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x05, 0x1A):
		return setting_default_uint16_to_bytes((uint16_t)(250), bytes, len);
	case MAKE_KEY(0x05, 0x1B):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x05, 0x1C):
		return setting_default_uint32_to_bytes((uint32_t)(150000), bytes, len);
	case MAKE_KEY(0x05, 0x1D):
		return setting_default_uint16_to_bytes((uint16_t)(18), bytes, len);
	case MAKE_KEY(0x05, 0x1E):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x05, 0x1F):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x05, 0x20):
		return setting_default_uint32_to_bytes((uint32_t)(869150000), bytes, len);
	case MAKE_KEY(0x05, 0x21):
		return setting_default_uint32_to_bytes((uint32_t)(869150000), bytes, len);
	case MAKE_KEY(0x05, 0x22): {
		if (len != 4) {
			return 0;
		}
		static const uint8_t default_value[4] = {0x07, 0x05, 0x01, 0x01};
		memcpy(bytes, default_value, sizeof(default_value));
		return 4;
	}
	case MAKE_KEY(0x05, 0x23): {
		if (len != 5) {
			return 0;
		}
		static const uint8_t default_value[5] = {0x00, 0x00, 0x0a, 0x01, 0x3c};
		memcpy(bytes, default_value, sizeof(default_value));
		return 5;
	}
	case MAKE_KEY(0x06, 0x00):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x06, 0x01):
		return setting_default_uint32_to_bytes((uint32_t)(156447700), bytes, len);
	case MAKE_KEY(0x06, 0x02):
		return setting_default_uint32_to_bytes((uint32_t)(465556280), bytes, len);
	case MAKE_KEY(0x06, 0x03):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x06, 0x04):
		return setting_default_uint32_to_bytes((uint32_t)(50), bytes, len);
	case MAKE_KEY(0x06, 0x05):
		return setting_default_uint8_to_bytes((uint8_t)(200), bytes, len);
	case MAKE_KEY(0x06, 0x06):
		return setting_default_uint8_to_bytes((uint8_t)(4), bytes, len);
	case MAKE_KEY(0x06, 0x07):
		return setting_default_uint16_to_bytes((uint16_t)(200), bytes, len);
	case MAKE_KEY(0x06, 0x08):
		return setting_default_uint16_to_bytes((uint16_t)(65), bytes, len);
	case MAKE_KEY(0x06, 0x09):
		return setting_default_uint8_to_bytes((uint8_t)(10), bytes, len);
	case MAKE_KEY(0x06, 0x0A):
		return setting_default_uint32_to_bytes((uint32_t)(0), bytes, len);
	case MAKE_KEY(0x06, 0x0B):
		return setting_default_uint8_to_bytes((uint8_t)(11), bytes, len);
	case MAKE_KEY(0x06, 0x0C):
		return setting_default_uint8_to_bytes((uint8_t)(5), bytes, len);
	case MAKE_KEY(0x06, 0x0D):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x06, 0x0E):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x06, 0x0F):
		return setting_default_uint32_to_bytes((uint32_t)(60), bytes, len);
	case MAKE_KEY(0x06, 0x10):
		return setting_default_uint8_to_bytes((uint8_t)(5), bytes, len);
	case MAKE_KEY(0x06, 0x11):
		return setting_default_uint8_to_bytes((uint8_t)(15), bytes, len);
	case MAKE_KEY(0x06, 0x12):
		return setting_default_uint8_to_bytes((uint8_t)(3), bytes, len);
	case MAKE_KEY(0x06, 0x13):
		return setting_default_uint8_to_bytes((uint8_t)(30), bytes, len);
	case MAKE_KEY(0x06, 0x14):
		return setting_default_uint8_to_bytes((uint8_t)(19), bytes, len);
	case MAKE_KEY(0x06, 0x15):
		return setting_default_uint8_to_bytes((uint8_t)(3), bytes, len);
	case MAKE_KEY(0x06, 0x16):
		return setting_default_uint8_to_bytes((uint8_t)(0), bytes, len);
	case MAKE_KEY(0x06, 0x17):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x06, 0x18):
		return setting_default_uint16_to_bytes((uint16_t)(0), bytes, len);
	case MAKE_KEY(0x07, 0x00):
		return setting_default_uint32_to_bytes((uint32_t)(86400), bytes, len);
	case MAKE_KEY(0x07, 0x01):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x07, 0x02):
		return setting_default_uint8_to_bytes((uint8_t)(10), bytes, len);
	case MAKE_KEY(0x07, 0x03):
		return setting_default_uint32_to_bytes((uint32_t)(86400), bytes, len);
	case MAKE_KEY(0x07, 0x04):
		return setting_default_uint8_to_bytes((uint8_t)(19), bytes, len);
	case MAKE_KEY(0x07, 0x05):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x07, 0x06):
		return setting_default_uint8_to_bytes((uint8_t)(7), bytes, len);
	case MAKE_KEY(0x08, 0x00):
		return setting_default_uint8_to_bytes((uint8_t)(6), bytes, len);
	case MAKE_KEY(0x08, 0x01):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x02):
		return setting_default_uint32_to_bytes((uint32_t)(60), bytes, len);
	case MAKE_KEY(0x08, 0x03):
		return setting_default_uint16_to_bytes((uint16_t)(10), bytes, len);
	case MAKE_KEY(0x08, 0x04):
		return setting_default_uint32_to_bytes((uint32_t)(100000), bytes, len);
	case MAKE_KEY(0x08, 0x05):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x06):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x07):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x08):
		return setting_default_uint16_to_bytes((uint16_t)(12), bytes, len);
	case MAKE_KEY(0x08, 0x09):
		return setting_default_uint8_to_bytes((uint8_t)(2), bytes, len);
	case MAKE_KEY(0x08, 0x0A):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x0B):
		return setting_default_uint8_to_bytes((uint8_t)(11), bytes, len);
	case MAKE_KEY(0x08, 0x0C): {
		if (len != 12) {
			return 0;
		}
		static const uint8_t default_value[12] = {0xCB, 0xEC, 0x6B, 0x12, 0x2A, 0x13,
							  0x79, 0x0F, 0x20, 0x1C, 0x00, 0x00};
		memcpy(bytes, default_value, sizeof(default_value));
		return 12;
	}
	case MAKE_KEY(0x08, 0x0E):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x0F):
		return setting_default_uint8_to_bytes((uint8_t)(0), bytes, len);
	case MAKE_KEY(0x08, 0x10):
		return setting_default_uint16_to_bytes((uint16_t)(50), bytes, len);
	case MAKE_KEY(0x08, 0x11):
		return setting_default_uint32_to_bytes((uint32_t)(3600), bytes, len);
	case MAKE_KEY(0x08, 0x12):
		return setting_default_uint8_to_bytes((uint8_t)(true), bytes, len);
	case MAKE_KEY(0x08, 0x13):
		return setting_default_uint16_to_bytes((uint16_t)(250), bytes, len);
	case MAKE_KEY(0x08, 0x14):
		return setting_default_uint8_to_bytes((uint8_t)(1), bytes, len);
	case MAKE_KEY(0x08, 0x15):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x16):
		return setting_default_uint8_to_bytes((uint8_t)(false), bytes, len);
	case MAKE_KEY(0x08, 0x17):
		return setting_default_uint32_to_bytes((uint32_t)(300), bytes, len);
	default:
		return 0;
	}
}

static bool setting_uint8_t_in_range(const value_uint8 *setting, uint8_t *data, uint8_t len)
{
	if (len != 1) {
		return false;
	}
	uint8_t value = data[0];
	return value >= setting->min && value <= setting->max;
}

static bool setting_uint32_t_in_range(const value_uint32 *setting, uint8_t *data, uint8_t len)
{
	if (len != 4) {
		return false;
	}
	uint32_t value = sys_get_le32(data);
	return value >= setting->min && value <= setting->max;
}

static bool setting_bool_in_range(const value_bool *setting, uint8_t *data, uint8_t len)
{
	if (len != 1) {
		return false;
	}
	uint8_t value = data[0];
	return value >= setting->min && value <= setting->max;
}

static bool setting_uint16_t_in_range(const value_uint16 *setting, uint8_t *data, uint8_t len)
{
	if (len != 2) {
		return false;
	}
	uint16_t value = sys_get_le16(data);
	return value >= setting->min && value <= setting->max;
}

static bool setting_int32_t_in_range(const value_int32 *setting, uint8_t *data, uint8_t len)
{
	if (len != 4) {
		return false;
	}
	int32_t value = (int32_t)sys_get_le32(data);
	return value >= setting->min && value <= setting->max;
}

bool setting_value_in_range(uint8_t family, uint8_t id, uint8_t *data, uint8_t len)
{
	if (data == NULL) {
		return false;
	}
	switch (MAKE_KEY(family, id)) {
	case MAKE_KEY(0x02, 0x00):
		return setting_uint8_t_in_range(Main_settings.tracker_type, data, len);
	case MAKE_KEY(0x02, 0x01):
		return setting_uint32_t_in_range(Main_settings.status_send_interval, data, len);
	case MAKE_KEY(0x02, 0x02):
		return setting_uint32_t_in_range(Main_settings.init_time, data, len);
	case MAKE_KEY(0x02, 0x03):
		return setting_bool_in_range(Main_settings.data_log, data, len);
	case MAKE_KEY(0x02, 0x04):
		return setting_uint32_t_in_range(Main_settings.wifi_scan_interval, data, len);
	case MAKE_KEY(0x02, 0x05):
		return setting_uint32_t_in_range(Main_settings.wifi_scan_aggregated_interval, data,
						 len);
	case MAKE_KEY(0x02, 0x06):
		return len == 8;
	case MAKE_KEY(0x02, 0x07):
		return len == 4;
	case MAKE_KEY(0x02, 0x08):
		return setting_bool_in_range(Main_settings.led_enabled, data, len);
	case MAKE_KEY(0x02, 0x09):
		return setting_uint32_t_in_range(Main_settings.memfault_send_interval, data, len);
	case MAKE_KEY(0x02, 0x0A):
		return setting_uint32_t_in_range(Main_settings.check_error_interval, data, len);
	case MAKE_KEY(0x02, 0x0B):
		return setting_uint32_t_in_range(Main_settings.flash_status_interval, data, len);
	case MAKE_KEY(0x02, 0x0C):
		return setting_bool_in_range(Main_settings.wifi_scan_report_zero_connections_found,
					     data, len);
	case MAKE_KEY(0x03, 0x00):
		return setting_uint32_t_in_range(Main_settings.lr_send_flag, data, len);
	case MAKE_KEY(0x03, 0x01):
		return setting_uint32_t_in_range(Main_settings.flash_store_flag, data, len);
	case MAKE_KEY(0x03, 0x02):
		return setting_uint32_t_in_range(Main_settings.sat_send_flag, data, len);
	case MAKE_KEY(0x04, 0x00):
		return setting_bool_in_range(Main_settings.ble_adv, data, len);
	case MAKE_KEY(0x04, 0x01):
		return setting_uint32_t_in_range(Main_settings.ble_advertisement_interval, data,
						 len);
	case MAKE_KEY(0x04, 0x02):
		return setting_uint32_t_in_range(Main_settings.ble_scan_duration, data, len);
	case MAKE_KEY(0x04, 0x03):
		return setting_uint32_t_in_range(Main_settings.ble_scan_interval, data, len);
	case MAKE_KEY(0x04, 0x04):
		return setting_uint32_t_in_range(Main_settings.ble_scan_aggregated_interval, data,
						 len);
	case MAKE_KEY(0x04, 0x05):
		return setting_uint8_t_in_range(Main_settings.ble_scan_filter, data, len);
	case MAKE_KEY(0x04, 0x06):
		return setting_uint32_t_in_range(Main_settings.ble_auto_disconnect, data, len);
	case MAKE_KEY(0x04, 0x07):
		return setting_bool_in_range(Main_settings.ble_scan_report_zero_connections_found,
					     data, len);
	case MAKE_KEY(0x04, 0x08):
		return setting_bool_in_range(Main_settings.cmdq_enabled, data, len);
	case MAKE_KEY(0x04, 0x09):
		return setting_uint32_t_in_range(Main_settings.cmdq_scan_duration, data, len);
	case MAKE_KEY(0x04, 0x0A):
		return setting_uint32_t_in_range(Main_settings.cmdq_search_interval, data, len);
	case MAKE_KEY(0x04, 0x0B):
		return setting_uint32_t_in_range(Main_settings.cmdq_on_no_detection_wait_duration,
						 data, len);
	case MAKE_KEY(0x04, 0x0C):
		return len == 6;
	case MAKE_KEY(0x04, 0x0D):
		return setting_uint32_t_in_range(Main_settings.cmdq_reporting_interval, data, len);
	case MAKE_KEY(0x04, 0x0E):
		return setting_bool_in_range(Main_settings.cmdq_report_zero_messages_to_be_sent,
					     data, len);
	case MAKE_KEY(0x04, 0x0F):
		return setting_uint16_t_in_range(Main_settings.ble_scan_manufacturer_id, data, len);
	case MAKE_KEY(0x05, 0x00):
		return setting_uint32_t_in_range(Main_settings.lr_gps_interval, data, len);
	case MAKE_KEY(0x05, 0x01):
		return setting_bool_in_range(Main_settings.gnss_assisted_scan, data, len);
	case MAKE_KEY(0x05, 0x02):
		return setting_uint8_t_in_range(Main_settings.lr_adr, data, len);
	case MAKE_KEY(0x05, 0x03):
		return setting_uint8_t_in_range(Main_settings.lr_region, data, len);
	case MAKE_KEY(0x05, 0x04):
		return len == 16;
	case MAKE_KEY(0x05, 0x05):
		return len == 8;
	case MAKE_KEY(0x05, 0x06):
		return len == 8;
	case MAKE_KEY(0x05, 0x07):
		return setting_uint32_t_in_range(Main_settings.s_band_send_interval, data, len);
	case MAKE_KEY(0x05, 0x08):
		return setting_uint32_t_in_range(Main_settings.lr_join_flag, data, len);
	case MAKE_KEY(0x05, 0x09):
		return setting_uint32_t_in_range(Main_settings.lr_confirm_flag, data, len);
	case MAKE_KEY(0x05, 0x0A):
		return setting_uint16_t_in_range(Main_settings.lr_max_confirm_fail, data, len);
	case MAKE_KEY(0x05, 0x0B):
		return setting_uint32_t_in_range(Main_settings.lr_messaging_retry_interval, data,
						 len);
	case MAKE_KEY(0x05, 0x0C):
		return setting_uint8_t_in_range(Main_settings.lr_messaging_retry_count, data, len);
	case MAKE_KEY(0x05, 0x0D):
		return setting_uint32_t_in_range(Main_settings.rejoin_interval, data, len);
	case MAKE_KEY(0x05, 0x0E):
		return len == 16;
	case MAKE_KEY(0x05, 0x0F):
		return len == 16;
	case MAKE_KEY(0x05, 0x10):
		return len == 4;
	case MAKE_KEY(0x05, 0x11):
		return setting_uint32_t_in_range(Main_settings.s_band_rf_frequency_hz, data, len);
	case MAKE_KEY(0x05, 0x12):
		return setting_uint8_t_in_range(Main_settings.lr_adr_profile, data, len);
	case MAKE_KEY(0x05, 0x13):
		return setting_bool_in_range(Main_settings.vhf_enabled, data, len);
	case MAKE_KEY(0x05, 0x14):
		return setting_uint32_t_in_range(Main_settings.vhf_interval1, data, len);
	case MAKE_KEY(0x05, 0x15):
		return setting_uint32_t_in_range(Main_settings.vhf_interval2, data, len);
	case MAKE_KEY(0x05, 0x16):
		return setting_uint8_t_in_range(Main_settings.vhf_interval1_start, data, len);
	case MAKE_KEY(0x05, 0x17):
		return setting_uint8_t_in_range(Main_settings.vhf_interval2_start, data, len);
	case MAKE_KEY(0x05, 0x18):
		return setting_bool_in_range(Main_settings.vhf_multiple_intervals, data, len);
	case MAKE_KEY(0x05, 0x19):
		return setting_uint8_t_in_range(Main_settings.vhf_num_of_packets_per_burst, data,
						len);
	case MAKE_KEY(0x05, 0x1A):
		return setting_uint16_t_in_range(Main_settings.vhf_time_between_packets_ms, data,
						 len);
	case MAKE_KEY(0x05, 0x1B):
		return setting_bool_in_range(Main_settings.vhf_external_path, data, len);
	case MAKE_KEY(0x05, 0x1C):
		return setting_uint32_t_in_range(Main_settings.vhf_tx_frequency_khz, data, len);
	case MAKE_KEY(0x05, 0x1D):
		return setting_uint16_t_in_range(Main_settings.vhf_single_pulse_duration_ms, data,
						 len);
	case MAKE_KEY(0x05, 0x1E):
		return setting_uint8_t_in_range(Main_settings.s_band_send_mode, data, len);
	case MAKE_KEY(0x05, 0x1F):
		return setting_uint32_t_in_range(Main_settings.lp0_send_flag, data, len);
	case MAKE_KEY(0x05, 0x20):
		return setting_uint32_t_in_range(Main_settings.lp0_tx_frequency_hz, data, len);
	case MAKE_KEY(0x05, 0x21):
		return setting_uint32_t_in_range(Main_settings.lp0_rx_frequency_hz, data, len);
	case MAKE_KEY(0x05, 0x22):
		return len == 4;
	case MAKE_KEY(0x05, 0x23):
		return len == 5;
	case MAKE_KEY(0x06, 0x00):
		return setting_uint32_t_in_range(Main_settings.ublox_send_interval, data, len);
	case MAKE_KEY(0x06, 0x01):
		return setting_int32_t_in_range(Main_settings.gps_init_lon, data, len);
	case MAKE_KEY(0x06, 0x02):
		return setting_int32_t_in_range(Main_settings.gps_init_lat, data, len);
	case MAKE_KEY(0x06, 0x03):
		return setting_uint32_t_in_range(Main_settings.gps_resend_interval, data, len);
	case MAKE_KEY(0x06, 0x04):
		return setting_uint32_t_in_range(Main_settings.horizontal_accuracy, data, len);
	case MAKE_KEY(0x06, 0x05):
		return setting_uint8_t_in_range(Main_settings.cold_fix_retry, data, len);
	case MAKE_KEY(0x06, 0x06):
		return setting_uint8_t_in_range(Main_settings.hot_fix_retry, data, len);
	case MAKE_KEY(0x06, 0x07):
		return setting_uint16_t_in_range(Main_settings.cold_fix_timeout, data, len);
	case MAKE_KEY(0x06, 0x08):
		return setting_uint16_t_in_range(Main_settings.hot_fix_timeout, data, len);
	case MAKE_KEY(0x06, 0x09):
		return setting_uint8_t_in_range(Main_settings.gps_backoff_factor, data, len);
	case MAKE_KEY(0x06, 0x0A):
		return setting_uint32_t_in_range(Main_settings.ublox_send_interval_2, data, len);
	case MAKE_KEY(0x06, 0x0B):
		return setting_uint8_t_in_range(Main_settings.ublox_interval1_start, data, len);
	case MAKE_KEY(0x06, 0x0C):
		return setting_uint8_t_in_range(Main_settings.ublox_min_fix_time, data, len);
	case MAKE_KEY(0x06, 0x0D):
		return setting_bool_in_range(Main_settings.ublox_multiple_intervals, data, len);
	case MAKE_KEY(0x06, 0x0E):
		return setting_bool_in_range(Main_settings.ublox_active_tracking, data, len);
	case MAKE_KEY(0x06, 0x0F):
		return setting_uint32_t_in_range(Main_settings.gps_triggered_interval, data, len);
	case MAKE_KEY(0x06, 0x10):
		return setting_uint8_t_in_range(Main_settings.gps_skipped_triggered_interval, data,
						len);
	case MAKE_KEY(0x06, 0x11):
		return setting_uint8_t_in_range(Main_settings.ublox_leave_on, data, len);
	case MAKE_KEY(0x06, 0x12):
		return setting_uint8_t_in_range(Main_settings.gnss_constellation_to_use, data, len);
	case MAKE_KEY(0x06, 0x13):
		return setting_uint8_t_in_range(Main_settings.ublox_min_satellites_timer, data,
						len);
	case MAKE_KEY(0x06, 0x14):
		return setting_uint8_t_in_range(Main_settings.ublox_interval2_start, data, len);
	case MAKE_KEY(0x06, 0x15):
		return setting_uint8_t_in_range(Main_settings.ublox_min_satellites, data, len);
	case MAKE_KEY(0x06, 0x16):
		return setting_uint8_t_in_range(
			Main_settings.gps_motion_triggered_min_num_of_triggers_per_interval, data,
			len);
	case MAKE_KEY(0x06, 0x17):
		return setting_bool_in_range(Main_settings.enable_motion_trig_gps, data, len);
	case MAKE_KEY(0x06, 0x18):
		return setting_uint16_t_in_range(Main_settings.ublox_cold_fix_hour_interval, data,
						 len);
	case MAKE_KEY(0x07, 0x00):
		return setting_uint32_t_in_range(Main_settings.satellite_send_interval, data, len);
	case MAKE_KEY(0x07, 0x01):
		return setting_bool_in_range(Main_settings.satellite_enabled, data, len);
	case MAKE_KEY(0x07, 0x02):
		return setting_uint8_t_in_range(Main_settings.satellite_retry, data, len);
	case MAKE_KEY(0x07, 0x03):
		return setting_uint32_t_in_range(Main_settings.satellite_send_interval2, data, len);
	case MAKE_KEY(0x07, 0x04):
		return setting_uint8_t_in_range(Main_settings.satellite_send_interval2_start, data,
						len);
	case MAKE_KEY(0x07, 0x05):
		return setting_bool_in_range(Main_settings.satellite_multiple_intervals, data, len);
	case MAKE_KEY(0x07, 0x06):
		return setting_uint8_t_in_range(Main_settings.satellite_interval1_start, data, len);
	case MAKE_KEY(0x08, 0x00):
		return setting_uint8_t_in_range(Main_settings.motion_ths, data, len);
	case MAKE_KEY(0x08, 0x01):
		return setting_bool_in_range(Main_settings.fence_enabled, data, len);
	case MAKE_KEY(0x08, 0x02):
		return setting_uint32_t_in_range(Main_settings.fence_interval, data, len);
	case MAKE_KEY(0x08, 0x03):
		return setting_uint16_t_in_range(Main_settings.fence_sampling_length, data, len);
	case MAKE_KEY(0x08, 0x04):
		return setting_uint32_t_in_range(Main_settings.fence_mv_scaling_factor, data, len);
	case MAKE_KEY(0x08, 0x05):
		return setting_bool_in_range(
			Main_settings.external_switch_detection_gpio_pin_power_enabled, data, len);
	case MAKE_KEY(0x08, 0x06):
		return setting_bool_in_range(Main_settings.fence_led_blink, data, len);
	case MAKE_KEY(0x08, 0x07):
		return setting_bool_in_range(Main_settings.accel_movement_data_fifo_enabled, data,
					     len);
	case MAKE_KEY(0x08, 0x08):
		return setting_uint16_t_in_range(Main_settings.accel_odr_hz, data, len);
	case MAKE_KEY(0x08, 0x09):
		return setting_uint8_t_in_range(Main_settings.accel_g_scale, data, len);
	case MAKE_KEY(0x08, 0x0A):
		return setting_bool_in_range(Main_settings.outdoor_detection_enabled, data, len);
	case MAKE_KEY(0x08, 0x0B):
		return setting_uint8_t_in_range(Main_settings.outdoor_detection_tau, data, len);
	case MAKE_KEY(0x08, 0x0C):
		return len == 12;
	case MAKE_KEY(0x08, 0x0E):
		return setting_bool_in_range(Main_settings.external_switch_detection_enabled, data,
					     len);
	case MAKE_KEY(0x08, 0x0F):
		return setting_uint8_t_in_range(
			Main_settings.external_switch_detection_trigger_type, data, len);
	case MAKE_KEY(0x08, 0x10):
		return setting_uint16_t_in_range(
			Main_settings.external_switch_detection_trigger_debounce_ms, data, len);
	case MAKE_KEY(0x08, 0x11):
		return setting_uint32_t_in_range(
			Main_settings.external_switch_detection_reporting_interval, data, len);
	case MAKE_KEY(0x08, 0x12):
		return setting_bool_in_range(Main_settings.external_switch_send_inactivity_report,
					     data, len);
	case MAKE_KEY(0x08, 0x13):
		return setting_uint16_t_in_range(
			Main_settings.external_switch_minimal_report_duration_ms, data, len);
	case MAKE_KEY(0x08, 0x14):
		return setting_uint8_t_in_range(Main_settings.external_switch_input_pull, data,
						len);
	case MAKE_KEY(0x08, 0x15):
		return setting_bool_in_range(Main_settings.external_switch_counter_enabled, data,
					     len);
	case MAKE_KEY(0x08, 0x16):
		return setting_bool_in_range(Main_settings.air_quality_enabled, data, len);
	case MAKE_KEY(0x08, 0x17):
		return setting_uint32_t_in_range(Main_settings.air_quality_interval, data, len);
	default:
		return false;
	}
}

int set_setting_value_by_id(uint8_t family, uint8_t id, uint8_t *data, uint8_t len)
{
	switch (MAKE_KEY(family, id)) {
	case MAKE_KEY(0x02, 0x00):
		if (len == Main_settings.tracker_type->len) {
			Main_settings.tracker_type->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x01):
		if (len == Main_settings.status_send_interval->len) {
			Main_settings.status_send_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x02):
		if (len == Main_settings.init_time->len) {
			Main_settings.init_time->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x03):
		if (len <= Main_settings.data_log->len) {
			Main_settings.data_log->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x04):
		if (len == Main_settings.wifi_scan_interval->len) {
			Main_settings.wifi_scan_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x05):
		if (len == Main_settings.wifi_scan_aggregated_interval->len) {
			Main_settings.wifi_scan_aggregated_interval->def_val =
				bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x06):
		if (len <= Main_settings.device_name->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.device_name->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.device_name->len; i++) {
				Main_settings.device_name->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x07):
		if (len <= Main_settings.device_pin->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.device_pin->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.device_pin->len; i++) {
				Main_settings.device_pin->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x08):
		if (len <= Main_settings.led_enabled->len) {
			Main_settings.led_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x09):
		if (len == Main_settings.memfault_send_interval->len) {
			Main_settings.memfault_send_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x0A):
		if (len == Main_settings.check_error_interval->len) {
			Main_settings.check_error_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x0B):
		if (len == Main_settings.flash_status_interval->len) {
			Main_settings.flash_status_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x02, 0x0C):
		if (len <= Main_settings.wifi_scan_report_zero_connections_found->len) {
			Main_settings.wifi_scan_report_zero_connections_found->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x03, 0x00):
		if (len == Main_settings.lr_send_flag->len) {
			Main_settings.lr_send_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x03, 0x01):
		if (len == Main_settings.flash_store_flag->len) {
			Main_settings.flash_store_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x03, 0x02):
		if (len == Main_settings.sat_send_flag->len) {
			Main_settings.sat_send_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x00):
		if (len <= Main_settings.ble_adv->len) {
			Main_settings.ble_adv->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x01):
		if (len == Main_settings.ble_advertisement_interval->len) {
			Main_settings.ble_advertisement_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x02):
		if (len == Main_settings.ble_scan_duration->len) {
			Main_settings.ble_scan_duration->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x03):
		if (len == Main_settings.ble_scan_interval->len) {
			Main_settings.ble_scan_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x04):
		if (len == Main_settings.ble_scan_aggregated_interval->len) {
			Main_settings.ble_scan_aggregated_interval->def_val =
				bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x05):
		if (len == Main_settings.ble_scan_filter->len) {
			Main_settings.ble_scan_filter->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x06):
		if (len == Main_settings.ble_auto_disconnect->len) {
			Main_settings.ble_auto_disconnect->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x07):
		if (len <= Main_settings.ble_scan_report_zero_connections_found->len) {
			Main_settings.ble_scan_report_zero_connections_found->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x08):
		if (len <= Main_settings.cmdq_enabled->len) {
			Main_settings.cmdq_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x09):
		if (len == Main_settings.cmdq_scan_duration->len) {
			Main_settings.cmdq_scan_duration->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0A):
		if (len == Main_settings.cmdq_search_interval->len) {
			Main_settings.cmdq_search_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0B):
		if (len == Main_settings.cmdq_on_no_detection_wait_duration->len) {
			Main_settings.cmdq_on_no_detection_wait_duration->def_val =
				bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0C):
		if (len <= Main_settings.cmdq_searched_mac_address->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.cmdq_searched_mac_address->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.cmdq_searched_mac_address->len; i++) {
				Main_settings.cmdq_searched_mac_address->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0D):
		if (len == Main_settings.cmdq_reporting_interval->len) {
			Main_settings.cmdq_reporting_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0E):
		if (len <= Main_settings.cmdq_report_zero_messages_to_be_sent->len) {
			Main_settings.cmdq_report_zero_messages_to_be_sent->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x04, 0x0F):
		if (len == Main_settings.ble_scan_manufacturer_id->len) {
			Main_settings.ble_scan_manufacturer_id->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x00):
		if (len == Main_settings.lr_gps_interval->len) {
			Main_settings.lr_gps_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x01):
		if (len <= Main_settings.gnss_assisted_scan->len) {
			Main_settings.gnss_assisted_scan->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x02):
		if (len == Main_settings.lr_adr->len) {
			Main_settings.lr_adr->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x03):
		if (len == Main_settings.lr_region->len) {
			Main_settings.lr_region->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x04):
		if (len <= Main_settings.app_key->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.app_key->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.app_key->len; i++) {
				Main_settings.app_key->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x05):
		if (len <= Main_settings.device_eui->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.device_eui->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.device_eui->len; i++) {
				Main_settings.device_eui->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x06):
		if (len <= Main_settings.app_eui->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.app_eui->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.app_eui->len; i++) {
				Main_settings.app_eui->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x07):
		if (len == Main_settings.s_band_send_interval->len) {
			Main_settings.s_band_send_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x08):
		if (len == Main_settings.lr_join_flag->len) {
			Main_settings.lr_join_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x09):
		if (len == Main_settings.lr_confirm_flag->len) {
			Main_settings.lr_confirm_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0A):
		if (len == Main_settings.lr_max_confirm_fail->len) {
			Main_settings.lr_max_confirm_fail->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0B):
		if (len == Main_settings.lr_messaging_retry_interval->len) {
			Main_settings.lr_messaging_retry_interval->def_val =
				bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0C):
		if (len == Main_settings.lr_messaging_retry_count->len) {
			Main_settings.lr_messaging_retry_count->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0D):
		if (len == Main_settings.rejoin_interval->len) {
			Main_settings.rejoin_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0E):
		if (len <= Main_settings.lp0_app_key->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.lp0_app_key->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.lp0_app_key->len; i++) {
				Main_settings.lp0_app_key->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x0F):
		if (len <= Main_settings.lp0_network_key->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.lp0_network_key->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.lp0_network_key->len; i++) {
				Main_settings.lp0_network_key->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x10):
		if (len <= Main_settings.lp0_dev_addr->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.lp0_dev_addr->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.lp0_dev_addr->len; i++) {
				Main_settings.lp0_dev_addr->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x11):
		if (len == Main_settings.s_band_rf_frequency_hz->len) {
			Main_settings.s_band_rf_frequency_hz->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x12):
		if (len == Main_settings.lr_adr_profile->len) {
			Main_settings.lr_adr_profile->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x13):
		if (len <= Main_settings.vhf_enabled->len) {
			Main_settings.vhf_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x14):
		if (len == Main_settings.vhf_interval1->len) {
			Main_settings.vhf_interval1->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x15):
		if (len == Main_settings.vhf_interval2->len) {
			Main_settings.vhf_interval2->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x16):
		if (len == Main_settings.vhf_interval1_start->len) {
			Main_settings.vhf_interval1_start->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x17):
		if (len == Main_settings.vhf_interval2_start->len) {
			Main_settings.vhf_interval2_start->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x18):
		if (len <= Main_settings.vhf_multiple_intervals->len) {
			Main_settings.vhf_multiple_intervals->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x19):
		if (len == Main_settings.vhf_num_of_packets_per_burst->len) {
			Main_settings.vhf_num_of_packets_per_burst->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1A):
		if (len == Main_settings.vhf_time_between_packets_ms->len) {
			Main_settings.vhf_time_between_packets_ms->def_val =
				bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1B):
		if (len <= Main_settings.vhf_external_path->len) {
			Main_settings.vhf_external_path->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1C):
		if (len == Main_settings.vhf_tx_frequency_khz->len) {
			Main_settings.vhf_tx_frequency_khz->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1D):
		if (len == Main_settings.vhf_single_pulse_duration_ms->len) {
			Main_settings.vhf_single_pulse_duration_ms->def_val =
				bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1E):
		if (len == Main_settings.s_band_send_mode->len) {
			Main_settings.s_band_send_mode->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x1F):
		if (len == Main_settings.lp0_send_flag->len) {
			Main_settings.lp0_send_flag->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x20):
		if (len == Main_settings.lp0_tx_frequency_hz->len) {
			Main_settings.lp0_tx_frequency_hz->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x21):
		if (len == Main_settings.lp0_rx_frequency_hz->len) {
			Main_settings.lp0_rx_frequency_hz->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x22):
		if (len <= Main_settings.lp0_communication_params->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.lp0_communication_params->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.lp0_communication_params->len; i++) {
				Main_settings.lp0_communication_params->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x05, 0x23):
		if (len <= Main_settings.lp0_node_params->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.lp0_node_params->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.lp0_node_params->len; i++) {
				Main_settings.lp0_node_params->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x00):
		if (len == Main_settings.ublox_send_interval->len) {
			Main_settings.ublox_send_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x01):
		if (len == Main_settings.gps_init_lon->len) {
			Main_settings.gps_init_lon->def_val = bytes_to_int32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x02):
		if (len == Main_settings.gps_init_lat->len) {
			Main_settings.gps_init_lat->def_val = bytes_to_int32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x03):
		if (len == Main_settings.gps_resend_interval->len) {
			Main_settings.gps_resend_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x04):
		if (len == Main_settings.horizontal_accuracy->len) {
			Main_settings.horizontal_accuracy->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x05):
		if (len == Main_settings.cold_fix_retry->len) {
			Main_settings.cold_fix_retry->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x06):
		if (len == Main_settings.hot_fix_retry->len) {
			Main_settings.hot_fix_retry->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x07):
		if (len == Main_settings.cold_fix_timeout->len) {
			Main_settings.cold_fix_timeout->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x08):
		if (len == Main_settings.hot_fix_timeout->len) {
			Main_settings.hot_fix_timeout->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x09):
		if (len == Main_settings.gps_backoff_factor->len) {
			Main_settings.gps_backoff_factor->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0A):
		if (len == Main_settings.ublox_send_interval_2->len) {
			Main_settings.ublox_send_interval_2->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0B):
		if (len == Main_settings.ublox_interval1_start->len) {
			Main_settings.ublox_interval1_start->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0C):
		if (len == Main_settings.ublox_min_fix_time->len) {
			Main_settings.ublox_min_fix_time->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0D):
		if (len <= Main_settings.ublox_multiple_intervals->len) {
			Main_settings.ublox_multiple_intervals->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0E):
		if (len <= Main_settings.ublox_active_tracking->len) {
			Main_settings.ublox_active_tracking->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x0F):
		if (len == Main_settings.gps_triggered_interval->len) {
			Main_settings.gps_triggered_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x10):
		if (len == Main_settings.gps_skipped_triggered_interval->len) {
			Main_settings.gps_skipped_triggered_interval->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x11):
		if (len == Main_settings.ublox_leave_on->len) {
			Main_settings.ublox_leave_on->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x12):
		if (len == Main_settings.gnss_constellation_to_use->len) {
			Main_settings.gnss_constellation_to_use->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x13):
		if (len == Main_settings.ublox_min_satellites_timer->len) {
			Main_settings.ublox_min_satellites_timer->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x14):
		if (len == Main_settings.ublox_interval2_start->len) {
			Main_settings.ublox_interval2_start->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x15):
		if (len == Main_settings.ublox_min_satellites->len) {
			Main_settings.ublox_min_satellites->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x16):
		if (len ==
		    Main_settings.gps_motion_triggered_min_num_of_triggers_per_interval->len) {
			Main_settings.gps_motion_triggered_min_num_of_triggers_per_interval
				->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x17):
		if (len <= Main_settings.enable_motion_trig_gps->len) {
			Main_settings.enable_motion_trig_gps->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x06, 0x18):
		if (len == Main_settings.ublox_cold_fix_hour_interval->len) {
			Main_settings.ublox_cold_fix_hour_interval->def_val =
				bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x00):
		if (len == Main_settings.satellite_send_interval->len) {
			Main_settings.satellite_send_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x01):
		if (len <= Main_settings.satellite_enabled->len) {
			Main_settings.satellite_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x02):
		if (len == Main_settings.satellite_retry->len) {
			Main_settings.satellite_retry->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x03):
		if (len == Main_settings.satellite_send_interval2->len) {
			Main_settings.satellite_send_interval2->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x04):
		if (len == Main_settings.satellite_send_interval2_start->len) {
			Main_settings.satellite_send_interval2_start->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x05):
		if (len <= Main_settings.satellite_multiple_intervals->len) {
			Main_settings.satellite_multiple_intervals->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x07, 0x06):
		if (len == Main_settings.satellite_interval1_start->len) {
			Main_settings.satellite_interval1_start->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x00):
		if (len == Main_settings.motion_ths->len) {
			Main_settings.motion_ths->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x01):
		if (len <= Main_settings.fence_enabled->len) {
			Main_settings.fence_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x02):
		if (len == Main_settings.fence_interval->len) {
			Main_settings.fence_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x03):
		if (len == Main_settings.fence_sampling_length->len) {
			Main_settings.fence_sampling_length->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x04):
		if (len == Main_settings.fence_mv_scaling_factor->len) {
			Main_settings.fence_mv_scaling_factor->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x05):
		if (len <= Main_settings.external_switch_detection_gpio_pin_power_enabled->len) {
			Main_settings.external_switch_detection_gpio_pin_power_enabled->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x06):
		if (len <= Main_settings.fence_led_blink->len) {
			Main_settings.fence_led_blink->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x07):
		if (len <= Main_settings.accel_movement_data_fifo_enabled->len) {
			Main_settings.accel_movement_data_fifo_enabled->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x08):
		if (len == Main_settings.accel_odr_hz->len) {
			Main_settings.accel_odr_hz->def_val = bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x09):
		if (len == Main_settings.accel_g_scale->len) {
			Main_settings.accel_g_scale->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x0A):
		if (len <= Main_settings.outdoor_detection_enabled->len) {
			Main_settings.outdoor_detection_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x0B):
		if (len == Main_settings.outdoor_detection_tau->len) {
			Main_settings.outdoor_detection_tau->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x0C):
		if (len <= Main_settings.outdoor_detection_parameters->len) {
			for (int i = 0; i < len; i++) {
				Main_settings.outdoor_detection_parameters->def_val[i] = data[i];
			}
			for (int i = len; i < Main_settings.outdoor_detection_parameters->len;
			     i++) {
				Main_settings.outdoor_detection_parameters->def_val[i] = '\0';
			}
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x0E):
		if (len <= Main_settings.external_switch_detection_enabled->len) {
			Main_settings.external_switch_detection_enabled->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x0F):
		if (len == Main_settings.external_switch_detection_trigger_type->len) {
			Main_settings.external_switch_detection_trigger_type->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x10):
		if (len == Main_settings.external_switch_detection_trigger_debounce_ms->len) {
			Main_settings.external_switch_detection_trigger_debounce_ms->def_val =
				bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x11):
		if (len == Main_settings.external_switch_detection_reporting_interval->len) {
			Main_settings.external_switch_detection_reporting_interval->def_val =
				bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x12):
		if (len <= Main_settings.external_switch_send_inactivity_report->len) {
			Main_settings.external_switch_send_inactivity_report->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x13):
		if (len == Main_settings.external_switch_minimal_report_duration_ms->len) {
			Main_settings.external_switch_minimal_report_duration_ms->def_val =
				bytes_to_uint16_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x14):
		if (len == Main_settings.external_switch_input_pull->len) {
			Main_settings.external_switch_input_pull->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x15):
		if (len <= Main_settings.external_switch_counter_enabled->len) {
			Main_settings.external_switch_counter_enabled->def_val =
				bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x16):
		if (len <= Main_settings.air_quality_enabled->len) {
			Main_settings.air_quality_enabled->def_val = bytes_to_uint8_t(data);
		} else {
			return -1;
		}
		break;
	case MAKE_KEY(0x08, 0x17):
		if (len == Main_settings.air_quality_interval->len) {
			Main_settings.air_quality_interval->def_val = bytes_to_uint32_t(data);
		} else {
			return -1;
		}
		break;
	default:
		return -1;
	}
	return 0;
}
