/* AUTOGENERATED FILE - DO NOT MODIFY! */
#ifndef SETTINGS_DEF_H_
#define SETTINGS_DEF_H_

#include "settings_types.h"
#include <stdio.h>
#include <zephyr/kernel.h>

#include "type_conversion.h"

typedef struct main_settings {
	value_uint8 *tracker_type;
	value_uint32 *lr_gps_interval;
	value_uint32 *ublox_send_interval;
	value_uint32 *status_send_interval;
	value_uint32 *satellite_send_interval;
	value_int32 *gps_init_lon;
	value_int32 *gps_init_lat;
	value_uint32 *init_time;
	value_bool *ble_adv;
	value_bool *gnss_assisted_scan;
	value_uint32 *gps_resend_interval;
	value_bool *data_log;
	value_uint32 *lr_send_flag;
	value_uint32 *flash_store_flag;
	value_uint8 *lr_adr;
	value_uint8 *lr_region;
	value_byte_array *app_key;
	value_byte_array *device_eui;
	value_byte_array *app_eui;
	value_uint32 *horizontal_accuracy;
	value_uint8 *cold_fix_retry;
	value_uint8 *hot_fix_retry;
	value_uint16 *cold_fix_timeout;
	value_uint16 *hot_fix_timeout;
	value_uint32 *ble_advertisement_interval;
	value_uint32 *wifi_scan_interval;
	value_uint32 *wifi_scan_aggregated_interval;
	value_uint32 *ble_scan_duration;
	value_uint32 *ble_scan_interval;
	value_uint32 *ble_scan_aggregated_interval;
	value_uint8 *ble_scan_filter;
	value_uint32 *ble_auto_disconnect;
	value_uint32 *s_band_send_interval;
	value_byte_array *device_name;
	value_uint32 *lr_join_flag;
	value_uint32 *lr_confirm_flag;
	value_uint16 *lr_max_confirm_fail;
	value_uint8 *gps_backoff_factor;
	value_uint32 *ublox_send_interval_2;
	value_uint8 *ublox_interval1_start;
	value_uint8 *ublox_min_fix_time;
	value_bool *ublox_multiple_intervals;
	value_byte_array *device_pin;
	value_bool *ublox_active_tracking;
	value_bool *led_enabled;
	value_uint8 *motion_ths;
	value_bool *enable_motion_trig_gps;
	value_uint32 *gps_triggered_interval;
	value_uint8 *gps_skipped_triggered_interval;
	value_uint32 *lr_messaging_retry_interval;
	value_uint8 *lr_messaging_retry_count;
	value_uint8 *ublox_leave_on;
	value_uint32 *memfault_send_interval;
	value_uint32 *rejoin_interval;
	value_uint32 *check_error_interval;
	value_uint8 *gnss_constellation_to_use;
	value_uint8 *ublox_min_satellites_timer;
	value_uint32 *sat_send_flag;
	value_bool *satellite_enabled;
	value_uint8 *satellite_retry;
	value_bool *fence_enabled;
	value_uint32 *fence_interval;
	value_uint16 *fence_sampling_length;
	value_uint32 *fence_mv_scaling_factor;
	value_uint32 *flash_status_interval;
	value_byte_array *lp0_app_key;
	value_byte_array *lp0_network_key;
	value_byte_array *lp0_dev_addr;
	value_bool *ble_scan_report_zero_connections_found;
	value_bool *wifi_scan_report_zero_connections_found;
	value_bool *cmdq_enabled;
	value_uint32 *cmdq_scan_duration;
	value_uint32 *cmdq_search_interval;
	value_uint32 *cmdq_on_no_detection_wait_duration;
	value_byte_array *cmdq_searched_mac_address;
	value_uint32 *cmdq_reporting_interval;
	value_uint32 *s_band_rf_frequency_hz;
	value_bool *cmdq_report_zero_messages_to_be_sent;
	value_uint8 *ublox_interval2_start;
	value_uint8 *lr_adr_profile;
	value_uint8 *ublox_min_satellites;
	value_bool *external_switch_detection_gpio_pin_power_enabled;
	value_bool *vhf_enabled;
	value_uint32 *vhf_interval1;
	value_uint32 *vhf_interval2;
	value_uint8 *vhf_interval1_start;
	value_uint8 *vhf_interval2_start;
	value_bool *vhf_multiple_intervals;
	value_uint8 *vhf_num_of_packets_per_burst;
	value_uint16 *vhf_time_between_packets_ms;
	value_bool *vhf_external_path;
	value_uint32 *vhf_tx_frequency_khz;
	value_uint16 *vhf_single_pulse_duration_ms;
	value_uint8 *s_band_send_mode;
	value_bool *fence_led_blink;
	value_uint8 *gps_motion_triggered_min_num_of_triggers_per_interval;
	value_uint16 *ble_scan_manufacturer_id;
	value_bool *accel_movement_data_fifo_enabled;
	value_uint16 *accel_odr_hz;
	value_uint8 *accel_g_scale;
	value_uint32 *satellite_send_interval2;
	value_uint8 *satellite_send_interval2_start;
	value_bool *satellite_multiple_intervals;
	value_uint8 *satellite_interval1_start;
	value_bool *outdoor_detection_enabled;
	value_uint8 *outdoor_detection_tau;
	value_byte_array *outdoor_detection_parameters;
	value_uint16 *ublox_cold_fix_hour_interval;
	value_bool *external_switch_detection_enabled;
	value_uint8 *external_switch_detection_trigger_type;
	value_uint16 *external_switch_detection_trigger_debounce_ms;
	value_uint32 *external_switch_detection_reporting_interval;
	value_bool *external_switch_send_inactivity_report;
	value_uint16 *external_switch_minimal_report_duration_ms;
	value_uint8 *external_switch_input_pull;
	value_bool *external_switch_counter_enabled;
	value_bool *air_quality_enabled;
	value_uint32 *air_quality_interval;
	value_uint32 *lp0_send_flag;
	value_uint32 *lp0_tx_frequency_hz;
	value_uint32 *lp0_rx_frequency_hz;
	value_byte_array *lp0_communication_params;
	value_byte_array *lp0_node_params;

	uint8_t n_settings;
	uint8_t *settings_id;
	uint8_t *settings_length;
} main_settings;

extern main_settings Main_settings;
int get_setting_by_id(uint8_t id, uint8_t *data);
void *get_setting_struct_by_id(uint8_t id);

int set_setting_value_by_id(uint8_t id, uint8_t *data, uint8_t len);

#endif
