/* AUTOGENERATED FILE - DO NOT MODIFY! */
#ifndef VALUES_DEF_H_
#define VALUES_DEF_H_

#include "settings_types.h"
#include <stdio.h>
#include <zephyr/kernel.h>

#include "type_conversion.h"

typedef struct main_values {
	value_uint32 *reset_reason;
	value_int32 *gps_lon;
	value_int32 *gps_lat;
	value_int32 *gps_alt;
	value_float *lis2_acc_x;
	value_float *lis2_acc_y;
	value_float *lis2_acc_z;
	value_int32 *batt_mV;
	value_uint32 *ublox_time;
	value_uint8 *lr_satellites;
	value_float *mcu_temp;
	value_int32 *charge_mV;
	value_uint16 *gps_h_acc_est;
	value_uint32 *flash_nr_msg;
	value_uint32 *last_position_time;
	value_uint32 *last_accel_int_time;
	value_uint8 *n_mes;
	value_uint16 *almanac_age;
	value_byte_array *factory_device_name;
	value_uint8 *satellite_resend_try;

	uint8_t n_values;
	uint8_t *values_id;
	uint8_t *values_length;
} main_values;

extern main_values Main_values;
void *get_value_struct_by_id(uint8_t id);
int get_value_by_id(uint8_t id, uint8_t *data);
int set_value_by_id(uint8_t id, uint8_t *data, uint8_t len);

#endif
