# Enable logging
CONFIG_PRINTK=y
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_LOG=y

#RTT
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_UART_CONSOLE=n

# Configure flash and gps enable pins
CONFIG_PERIPHERAL_POWER=y

# SPI
CONFIG_SPI=y
CONFIG_LR11XX_LIB=y
CONFIG_LR11XX_LOG_LEVEL_INF=y

CONFIG_ASSERT=y
CONFIG_DEBUG=y

CONFIG_MAIN_STACK_SIZE=4096

# Configure weather you are updating lr1110 or lr1120
# This will automatically include the latest transceiver firmware for that chip
# in main.c. Only set this if your specific board version is not present in the `boards/` folder.
# If a configuration file is present for your specific board it will overwrite the below set configuration.

# CONFIG_UPDATE_LR1110=n
# CONFIG_UPDATE_LR1120=n
