CONFIG_GPIO=y
CONFIG_SERIAL=y

# Enable RTT logging
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG=y

# UART async API must not be enabled if we want to use the UART polling API
# CONFIG_UART_ASYNC_API=n
