#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Nordic
#
CONFIG_NEWLIB_LIBC=y
CONFIG_REBOOT=y

# Enable UART driver
CONFIG_GPIO=y
CONFIG_SERIAL=y

CONFIG_HEAP_MEM_POOL_SIZE=4096

#BT
CONFIG_BT=y
# Peripheral device
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
# Allow setting BT power
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_LL_SW_SPLIT=y
# NUS service
CONFIG_BT_NUS=y
# Advertisement
CONFIG_BT_BROADCASTER=y
# Scanning
CONFIG_BT_OBSERVER=y

# DFU
# Enable mcumgr management library
CONFIG_MCUMGR=y
# Enable image and os management
CONFIG_MCUMGR_CMD_IMG_MGMT=y
CONFIG_MCUMGR_CMD_OS_MGMT=y

# BT sizes
CONFIG_BT_L2CAP_TX_MTU=252
CONFIG_BT_BUF_ACL_RX_SIZE=256
 # was 248 EvaTODO
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_RX_STACK_SIZE=2048

# Enable the Bluetooth (unauthenticated) and shell mcumgr transports.
CONFIG_MCUMGR_SMP_BT=y
CONFIG_MCUMGR_SMP_BT_AUTHEN=n

# Do we need this? EvaTODO
CONFIG_BT_DEVICE_APPEARANCE=833

# NVS read/write
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_NVS=y
#CONFIG_SETTINGS_NVS=y
#CONFIG_SETTINGS=y
#CONFIG_FLASH=y
#CONFIG_FLASH_MAP=y

# This example requires more workqueue stack
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# MCUBOOT
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MULTITHREADING=y

CONFIG_MAIN_STACK_SIZE=24384

# Required by the `taskstat` command.
CONFIG_THREAD_MONITOR=y

# Sensors - rest in individual board definitions
CONFIG_SENSORS_MODULE=y

CONFIG_STDOUT_CONSOLE=y

# lr11xx
CONFIG_SPI=y
CONFIG_LR11XX_LIB=y
CONFIG_LR11XX_LOG_LEVEL_DBG=y
CONFIG_LORA_BASICS_MODEM=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_LORA_BASICS_MODEM_USER_STORAGE_IMPL=y

# External flash
CONFIG_FLASH_MODULE=y

# voltage divider
CONFIG_ADC=y
CONFIG_VOLTAGE_DIVIDER=y

#Watchdog
CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=n

# Low power setting - see Kconfig for config dependencies
CONFIG_LOW_POWER=y

# Logging needs to be disabled for low power
CONFIG_LOG=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_SHELL_BACKEND_SERIAL=n

# External modules
CONFIG_UART_INTERRUPT_DRIVEN=y # Test external modules UART

CONFIG_PERIPHERAL_POWER=y

# Use version lib
CONFIG_VERSION_INFO=y

# Needed for UBLOX
CONFIG_CPLUSPLUS=y

# Lis2dw12 (accelerometer) FIFO
CONFIG_IRNAS_LIS2DW12_FIFO=y

CONFIG_LORAWAN_TOOLS=y # LUKATODO:TODO-FUTURE: remove when s-band is completely moved to LP0
# Internal libraries
CONFIG_LP0_COMMUNICATION=y
# for base64 encoding
CONFIG_BASE64=y
